### ISSUE TITLE
Go: Invalid Go code output for curl command

### ISSUE THREAD

**Issue by palash25** [curlconverter/curlconverter#124]
curl command

```shell
curl --location --request POST "http://foo:bar@localhost:8000/_reindexer/bank" \
  --header "Content-Type: application/json" \
  --data "{}"
```

```go
package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
)

func main() {
	client := &http.Client{}
	var data = []byte(`{{}}`)
	req, err := http.NewRequest("POST", "http://foo:bar@localhost:8000/_reindexer/bank", data)
	if err != nil {
		log.Fatal(err)
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := client.Do(req)
	if err != nil {
		log.Fatal(err)
	}
	bodyText, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%s\n", bodyText)
}

```

The problem with this output is that it sends a slice of bytes as the response body `req, err := http.NewRequest("POST", "http://foo:bar@localhost:8000/_reindexer/bank", data)`

but since `[]byte` doesn't implement an `io.Reader` it won't be accepted as an argument to the method and this couldn't would give errors.

Instead the output should be something like this `req, _ := http.NewRequest("POST", fmt.Sprintf("%s%s", mockLogsServer.URL, tt.path), bytes.NewBuffer(data))`

**Comment by codenoid** [comment]
#212
