### ISSUE TITLE
cookies variable is empty if copying cURL command from Chrome DevTools

### ISSUE THREAD

**Issue by iamumairayub** [curlconverter/curlconverter#125]
When I copy cURL command from Firefox Devtools and convert to Python, it works perfectly like

> 
> headers = {
> #some headers here
> }
> cookies = {
> #some cookies here
> }

But if I copy cURL (bash) command and convert to Python, the cookies are present inside headers variable, but cookies variable is empty, I get code like this
> 
> headers = {
> "cookies": "cookies here"
> }
> cookies = {
> }

**Comment by cf512** [comment]
I would like to replicate and look into further. Please reply with some complete input examples.

**Comment by verhovsky** [comment]
We can't fix this issue without seeing the original curl command that produces it, so I'm closing this issue. 

Hopefully the changes in the last 3 years have fixed whatever was causing this.
