### ISSUE TITLE
Incorrect code for retrieving a session

### ISSUE THREAD

**Issue by yifan-xiang** [curlconverter/curlconverter#133]
The work flow in terminal is:
1)
curl https://api.stripe.com/v1/reporting/report_runs \
  -u key\
  -d report_type="balance_change_from_activity.summary.1" \
  -d parameters[interval_start]=1522540800 \
  -d parameters[interval_end]=1525132800 

This command will start a report_run session, where I can find session id in the response. When the session is complete:

2)
curl https://api.stripe.com/v1/reporting/report_runs /sessions/seesion_id
  -u key

This will lead me to the url or generated report.

It works fine in terminal. However, if I translate it into python, only 1) works. I got error "Unrecognized request URL" for 2).

Can anyone tell me what should be the correct way to retrieve the session given session id?

Thanks!

**Comment by cf512** [comment]
Is it possibly just unrecognized because of a typo in the second curl? The info provided says `seesion_id` rather than `session_id`.

**Comment by verhovsky** [comment]
The other problem with your second command is that there's a space between `report_runs` and `/sessions/seesion_id`. I think this is no longer an issue.
