### ISSUE TITLE
CURL -f post image convert to python not worked

### ISSUE THREAD

**Issue by QQ601407388** [curlconverter/curlconverter#137]
curl -X POST "http://173.193.92.174:31070/model/predict" -H "Content-Type: multipart/form-data" -F "image=@me.jpg" 

convert to python:
import requests
headers = {
    'Content-Type': 'multipart/form-data',
}
files = {
    'image': ('me.jpg', open('me.jpg', 'rb')),
}
response = requests.post('http://173.193.92.174:31070/model/predict', headers=headers, files=files)

the python code not worked ,
response :
400 bad request
![捕获](https://user-images.githubusercontent.com/3212074/60444007-e97a4f80-9c4e-11e9-8e20-b23791685540.JPG)

**Comment by verhovsky** [comment]
Try commenting out the `Content-Type` line, this is probably the same issue as #248
