### ISSUE TITLE
Unable to convert Curl to Python

### ISSUE THREAD

**Issue by shamalmhetre** [curlconverter/curlconverter#156]
Unable to convert below Curl command to Python

curl --form addressFile=@localfile.csv --form benchmark=9
#https://geocoding.geo.census.gov/geocoder/locations/addressbatch --output geocoderesult.csv

**Comment by jgroom33** [comment]
What is the `#` before the https?

**Comment by shamalmhetre** [comment]
Sorry for that. "#" needs to be removed. By the way I was able to make it work in Python using requests by replacing with this

import requests

url = 'https://geocoding.geo.census.gov/geocoder/locations/addressbatch'
filename = 'C:/Users/.........../Sample2.txt'

files = {
    'benchmark': (None, 9),
    'addressFile': (filename, open(filename, 'rb')),
}

response = requests.post(url, files=files)

**Comment by jgroom33** [comment]
Are you requesting that `--form` be supported as an input parameter for python? Or are you requesting that `@` file syntax be supported? If so, the title of this issue should be updated

**Comment by verhovsky** [comment]
We have supported `--form` and `@` file syntax for it for a while. With #349 we now also support `--output` so everything about this command should convert correctly:

```py
import requests

files = {
    'addressFile': ('localfile.csv', open('localfile.csv', 'rb')),
    'benchmark': (None, '9'),
}

response = requests.post('https://geocoding.geo.census.gov/geocoder/locations/addressbatch', files=files)

with open('geocoderesult.csv', 'wb') as f:
    f.write(response.content)
```
