### ISSUE TITLE
Improperly parsing form data

### ISSUE THREAD

**Issue by elliott-king** [curlconverter/curlconverter#178]
It seems to be having an issue when the form data is a complex dict/object. I attempted this w/ both firefox and chrome, same issues both time.

[Here ](https://gist.github.com/elliott-king/8492ad010035f2eef27cfd2f897e8381)is a gist of the curl request, with the return.

Notice how the first piece of the data field has several unclosed brackets. Their corresponding closing brackets can be found in one of the 'facetfilters' field. Interestingly enough, it seems that FF and Chrome are also incorrectly parsing them, and have the same issue in the 'Form Data' section. The 'uncurl' python library also seems to fail.

I can work around it by entering the form data as one string.

**Comment by elliott-king** [comment]
In python, response.text shows:
`'{"message":"lexical error: invalid char in json text. Around \'%7B%22requ\' near line:1 column:1","status":400}'`

**Comment by verhovsky** [comment]
I think this is the same issue as #334 and after #340 your data string is no longer converted to a Python object, it just stays as a string.
