### ISSUE TITLE
0x0.st upload

### ISSUE THREAD

**Issue by cement78** [curlconverter/curlconverter#195]
curl -F'file=@yourfile.png' https://0x0.st

**Comment by romadrutskii** [comment]
> 
> 
> curl -F'file=@yourfile.png' https://0x0.st

Actually the service doesn't parse if there is no space between option and argument. You should type `curl -F 'file=@yourfile.png' https://0x0.st` instead.

**Comment by verhovsky** [comment]
Curl does let you omit the space between a short argument and the value passed to it, and so does curlconverter since #278
