### ISSUE TITLE
Can anyone please help me converting code from curl to ansible ui

### ISSUE THREAD

**Issue by ashu-khantwal** [curlconverter/curlconverter#196]
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Token: *******' -d '{ \ 
   "notification": "Errors_Or_Warnings", \ 
   "emailConfiguration": { \ 
     "fromAddress": "n@abc.com", \ 
     "listOfToAddresses": [ \ 
       "a@abc.com" \ 
     ], \ 
     "subject": "Alert" \ 
   }, \ 
   "entities": [ \ 
     "datastore-161456" \ 
   ], \ 
   "isCustomSnapshot": false, \ 
   "name": "esx03", \ 
   "description": "esx03", \ 
  "policies": [ \ 
           { \ 
             "id": "0", \ 
             "name": "DR", \ 
             "scheduleType": "DAILY", \ 
             "schedule": { \ 
               "startDate": "2020-02-07", \ 
               "startMinute": "27", \ 
               "reccurrenceForHourlyPolicy": 0, \ 
               "reccurrenceForDailyPolicy": 1, \ 
               "startHour": "2" \ 
             } \ 
           } \ 
         ], \ 
   "spanningDatastores": { \ 
     "spanningType": "EXCLUDE_ALL" \ 
   } \ 
 }' 'https://abc@xyz.com/api/groups'

**Comment by romadrutskii** [comment]
> 
> 
> curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Token: *******' -d '{ \
> "notification": "Errors_Or_Warnings", \
> "emailConfiguration": { \
> "fromAddress": "[n@abc.com](mailto:n@abc.com)", \
> "listOfToAddresses": [ \
> "[a@abc.com](mailto:a@abc.com)" \
> ], \
> "subject": "Alert" \
> }, \
> "entities": [ \
> "datastore-161456" \
> ], \
> "isCustomSnapshot": false, \
> "name": "esx03", \
> "description": "esx03", \
> "policies": [ \
> { \
> "id": "0", \
> "name": "DR", \
> "scheduleType": "DAILY", \
> "schedule": { \
> "startDate": "2020-02-07", \
> "startMinute": "27", \
> "reccurrenceForHourlyPolicy": 0, \
> "reccurrenceForDailyPolicy": 1, \
> "startHour": "2" \
> } \
> } \
> ], \
> "spanningDatastores": { \
> "spanningType": "EXCLUDE_ALL" \
> } \
> }' 'https://abc@xyz.com/api/groups'

Could you clarify the issue? The converter parses fine.

**Comment by verhovsky** [comment]
The issue I see is that your `--data`/`-d` is wrapped in `'`, but you still escape the newline characters which doesn't work in bash, so you end up with backslashes in your JSON and invalid JSON. Instead of

```
curl --header 'Content-Type: application/json' -d '{ \
"notification": "Errors_Or_Warnings", \
"emailConfiguration": "abc" \
}'
```

you should just do

```
curl --header 'Content-Type: application/json' -d '{
"notification": "Errors_Or_Warnings",
"emailConfiguration": "abc"
}'
```
