### ISSUE TITLE
support reading cookies from file

### ISSUE THREAD

**Issue by alexsuslin** [curlconverter/curlconverter#199]
`curl -b cookie.txt http://posttestserver.com/post.php`

**Comment by verhovsky** [comment]
@alexsuslin what do you expect the generated code to look like?

I think people use `-b` almost always with `-c`, like this `curl -b cookie.txt -c cookie.txt http://posttestserver.com/post.php`, to get curl to persist cookies as you're running multiple commands. curl saves and expects cookies as essentially a tsv file (tab separated values, like csv but with Tabs) with `#` comments.

https://curl.se/docs/http-cookies.html

If we're just talking about Python, do you expect it to output a short program that reads and parses this tsv format, something like

```
import requests

with open('cookies.txt') as f:
    cookie_lines = [l for l in f if l.strip() and not l.strip().startswith('#')]
    cookies = dict(l.split('\t')[5:8] for l in cookie_lines)

response = requests.get('http://posttestserver.com/post.php', cookies=cookies)
```

or do you expect it to do it in a more pythonic way? There's no standard way to store/read cookies in a file in Python, people on https://stackoverflow.com/questions/13030095/how-to-save-requests-python-cookies-to-a-file are either serializing the cookies as JSON or [`pickle`ing CookieJar objects](https://stackoverflow.com/a/33280666), which seems like the best way.
