### ISSUE TITLE
conversion is not working for a certain types

### ISSUE THREAD

**Issue by anagilla** [curlconverter/curlconverter#214]
curl -s -X POST "http://$DomainHostName:$ROHPort/DataIntegrationService/modules/core/v1/applications/$applicationName/state" -H  "accept:application/json" -H  "username:$domainUserName" -H  "encryptedpassword:$domainEncryptedPassword" -H  "securitydomain:$DomainName" -H  "Content-Type:application/json" -d "{  \"action\": \"stop\"}"

**Comment by romadrutskii** [comment]
> 
> 
> curl -s -X POST "http://$DomainHostName:$ROHPort/DataIntegrationService/modules/core/v1/applications/$applicationName/state" -H "accept:application/json" -H "username:$domainUserName" -H "encryptedpassword:$domainEncryptedPassword" -H "securitydomain:$DomainName" -H "Content-Type:application/json" -d "{ "action": "stop"}"

Could you please clarify the issue?

**Comment by verhovsky** [comment]
Closing this as a duplicate of #226
