### ISSUE TITLE
web tool ignoring several options

### ISSUE THREAD

**Issue by marozsas** [curlconverter/curlconverter#221]
The following curl command:
curl --silent --output /dev/null --data-urlencode "some_text_here" --data-urlencode "another text here" --data-urlencode "text=any text here"  "https://www.site.com/whatever"

is converted to:

response = requests.get('https://www.site.com/whatever')

it is missing several options in the original command line.

**Comment by verhovsky** [comment]
I don't see the need to support `--silent` and `--output /dev/null`. The other arguments convert just fine now.

Testing with `nc -kl 8888`, this command

`curl --silent --output /dev/null --data-urlencode "some_text_here" --data-urlencode "another text here" --data-urlencode "text=any text here" localhost:8888`

looks like this:

```
POST / HTTP/1.1
Host: localhost:8888
User-Agent: curl/7.77.0
Accept: */*
Content-Length: 51
Content-Type: application/x-www-form-urlencoded

some_text_here&another+text+here&text=any+text+here
```

We currently convert it to this Python code

```py
import requests

data = {
  'some_text_here': '',
  'another text here': '',
  'text': 'any text here'
}

response = requests.get('http://localhost:8888', data=data)
```

which looks like this

```
GET / HTTP/1.1
Host: localhost:8888
User-Agent: python-requests/2.26.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 53
Content-Type: application/x-www-form-urlencoded

some_text_here=&another+text+here=&text=any+text+here
```

but after the changes in #340, we don't convert it to a dict anymore

```py
import requests

data = 'some_text_here&another text here&text=any text here'

response = requests.get('http://localhost:8888', data=data)
```

which actually doesn't send entirely the same data as the original request (we'll would have to convert spaces to `+` for that)

```
GET / HTTP/1.1
Host: localhost:8888
User-Agent: python-requests/2.26.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 51

some_text_here&another text here&text=any text here
```
