### ISSUE TITLE
Support username:password in URL

### ISSUE THREAD

**Issue by szabgab** [curlconverter/curlconverter#222]
```
curl http://foo:secret/bar@example.com
```

converts in python to:

```
import requests

response = requests.get('http://foo/:secret/bar@example.com')
```
but this gives an invalid URL error. (There is also a trailing slash after foo.)

If I am not mistaken this conversion would be more generic:

```
import requests

response = requests.get('http://example.com', auth=('foo', 'secret/bar'))
```

**Comment by verhovsky** [comment]
The only issue here was the extra `/` after `foo` in the generated code's URL. These days this is fixed and we convert that command to

```py
import requests

response = requests.get('http://foo:secret/bar@example.com')
```

which is valid Requests code, it lets you put the username/password in the URL like that, just like curl.
