### ISSUE TITLE
don't use this package

### ISSUE THREAD

**Issue by lonewolfyx** [curlconverter/curlconverter#247]
When I install this project and package it, it prompts me that I need to install "child_process" and "fs"packages. Unfortunately, there are no contents of this project package under NPM. Can you solve this problem?

**Comment by NickCarneiro** [comment]
Can you post the output of `npm install`?

This is what it looks like for me on ubuntu 20.04.

```
nick@foo:~/development/npmtest$ npm install curlconverter
npm WARN saveError ENOENT: no such file or directory, open '/home/nick/development/npmtest/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open '/home/nick/development/npmtest/package.json'
npm WARN npmtest No description
npm WARN npmtest No repository field.
npm WARN npmtest No README data
npm WARN npmtest No license field.

+ curlconverter@3.12.0
added 56 packages from 42 contributors and audited 57 packages in 4.082s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by NickCarneiro** [comment]
`child_process` and `fs` are build into the node standard library: 
https://nodejs.org/api/child_process.html
https://nodejs.org/api/fs.html

**Comment by lonewolfyx** [comment]
node version ：`12.18.4`

**Comment by lonewolfyx** [comment]
The problem is to execute NPX execution for it webpack.config.js Appears when packing

**Comment by NickCarneiro** [comment]
Can you give me some steps to reproduce this?

**Comment by verhovsky** [comment]
I think this issue is because when you try to use a node library in the browser you need to tell webpack where to get the `fs` module. You can see how we do it in our webpack config for curlconverter.com

```js
  resolve: {
    fallback: {
      url: require.resolve('url/'),
      path: require.resolve('path-browserify'),
      fs: false
    }
  },
```

https://github.com/curlconverter/curlconverter.github.io/blob/446afd773f10311ded2d0cfae61ec599b59e9c66/webpack.config.js#L35-L37

I'm not sure if all 3 of those are necessary.
