### ISSUE TITLE
can't install dependency yargs in docker

### ISSUE THREAD

**Issue by prabak** [curlconverter/curlconverter#261]
Why did the `yargs` dependency change from `"yargs": "github:NickCarneiro/yargs"` to `"yargs": "git@github.com:NickCarneiro/yargs-ansi.git"`? My docker is erroring out now:

```bash
#20 20.53 npm ERR! prepareGitDep npm ERR! Error while executing:
#20 20.53 npm ERR! prepareGitDep npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/NickCarneiro/yargs-parser-ansi.git
#20 20.53 npm ERR! prepareGitDep npm ERR!
#20 20.53 npm ERR! prepareGitDep npm ERR! Host key verification failed.
#20 20.53 npm ERR! prepareGitDep npm ERR! fatal: Could not read from remote repository.
```

**Comment by LucaGambaro** [comment]
Same problem, for now, i solved by deleting the dependency

`npm uninstall yargs`
and then 
`npm i --save yargs`

after this, i linked the library with
`npm link`
and relinked in the new project
`npm link curlconverter`

And seems to work

**Comment by mustafafrw** [comment]
Same problem, I could not solved

**Comment by arshxyz** [comment]
Same problem, the issue seems to arise from `yargs` being pulled from a a git repo instead of npm.

**Comment by verhovsky** [comment]
According to https://stackoverflow.com/a/29380765 , this can be solved by saving GitHub's SSH key, like this

```sh
ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
```

before running `npm install curlconverter`.

**Comment by verhovsky** [comment]
We published our fork of yargs on npm as `@curlconverter/yargs`, so it should no longer be possible for you to get this error if you upgrade to curlconverter 3.21.0+
