### ISSUE TITLE
can't install via yarn

### ISSUE THREAD

**Issue by Nishchit14** [curlconverter/curlconverter#269]
`yarn add curlconverter` command fires this error. unable to install the lib. please help here if possible. and many thanks for creating this curl converter utility. It seems very helpful :)

```
yarn add curlconverter
yarn add v1.22.5
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/NickCarneiro/yargs-ansi.git
Directory: /User/-----path/--
Output:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by NickCarneiro** [comment]
Dependency on yargs-ansi will likely be moved to verhovsky's yargs fork soon which may mitigate this.

**Comment by verhovsky** [comment]
We published our fork of yargs on npm as `@curlconverter/yargs`, so you should no longer get this error if you upgrade to 3.21.0+
