### ISSUE TITLE
Converting to Go can cause errors when request headers contain "

### ISSUE THREAD

**Issue by georgepittock** [curlconverter/curlconverter#272]
To reproduce:

```
curl 'https://github.com/NickCarneiro/curlconverter' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="92"' \
  --compressed
```
Can easily be fixed by using ` instead of ".

**Comment by NickCarneiro** [comment]
Sorry, I reverted this because it seems like the backticks would have the same issue.

Is it possible to escape the double quotes?
