### ISSUE TITLE
Error with string content have ‘=’ in it

### ISSUE THREAD

**Issue by AkerIII** [curlconverter/curlconverter#277]
for example：

> --data-raw '{"message":"a plus b=1"}' 

then we get

> data = {
>   '{"message":"a plus b': '1"}'
> }

what we need under python3 is

> data = '{"message":"a plus b=1"}'

notice that the '{}'here is not needed and may cause an exception when post.

**Comment by verhovsky** [comment]
This issues wasn't caused by bash parsing. Tree-sitter parses `echo '{"message":"a plus b=1"}'` correctly, so this must be an issue in curlconverter.

**Comment by nilay1221** [comment]
@verhovsky Yeah this is caused because of querystring library as it splits along "=" sign.
https://github.com/curlconverter/curlconverter/blob/661b29d8c1b1c2b8e8da1bbeeda9b7bc2e670e22/generators/python.js#L49

Why don't we directly use the string returned by the bash parsing as we are doing in node-request? Because there is no need of creating dict in python as we can directly use string for making requests.

**Comment by verhovsky** [comment]
@nilay1221 because the string can be often be like 1,000+ characters long for many requests made in the web browser and it's helpful in those cases to be able to see it as a dictionary.

**Comment by nilay1221** [comment]
> @nilay1221 because when the query string is 1,000+ characters long it's helpful to be able to see and edit it as a dictionary, plus putting a really long string in your code doesn't look good.


Thank you for looking into the issue . But for JSON data we are not converting to dict we are just extracting out the string. 
![image](https://user-images.githubusercontent.com/44199023/145667544-50777d15-91c0-4517-8111-0f801f04379f.png)

Could we have prior check if the data is json or url-encoded using headers? That would help us solve this issue.

**Comment by verhovsky** [comment]
Noticing that the `--data` being uploaded is JSON and generating code like

```
json_data = {
    'name': 'nilay',
    'job': 'leader',
}

requests.post(url, json=json_data)

# The JSON data as it appears in the original request may be formatted
# differently than converting the parsed Python object to JSON
# data = '{"name": "nilay", "job": "leader"}'
# requests.post(url, data=data)
```

makes total sense and I hope to do it eventually, but I want to finish #303 first.

**Comment by nilay1221** [comment]
I tried doing this and came up with this
```javascript
if(request.headers && request.headers['Content-Type'] === 'application/json'){
		const jsonObj = JSON.parse(request.data);
		let prettifiedStr = JSON.stringify(jsonObj,null,' ');
		prettifiedStr = prettifiedStr.replaceAll('true','True');
		return 'data = ' + prettifiedStr + '\n';
}
```
So for input

`'{"message":"a plus true","status":true,"num":3.5,"a":{"b":true}}'`

I am getting this output

```python
data = {
 "message": "a plus True",
 "status": True,
 "num": 3.5,
 "a": {
  "b": True
 }
}
```

There is one caveat of converting boolean values. As it replaces string values containing _true_ to also _True_. Any idea how could i solve that problem?

Thank you

**Comment by nilay1221** [comment]
I tried this and came up with this 
```javascript
if(request.headers && request.headers['Content-Type'] === 'application/json'){
		let jsonObj = JSON.parse(request.data);
		let prettifiedStr = JSON.stringify(jsonObj,null,' ');
		prettifiedStr = prettifiedStr.replaceAll('true','True').replaceAll('false','False').replaceAll('null','None');
		return 'data = ' + prettifiedStr + '\n';
}

```
So with this input
 
`'{"message":"a plus=true","status":true,"num":3.5,"a":{"b":true},"d":null}'`

I get this output

```python
data = {
 "message": "a plus=True",
 "status": True,
 "num": 3.5,
 "a": {
  "b": True
 },
 "d": None
}
```
Now the problem is that it would replace string values containing (true,false,null) with (True,False,None) respectively. Any idea how could i solve this problem?
One i can think of is to iterate the jsonObj manually and then create the data string.

Thank you

**Comment by verhovsky** [comment]
You can't do `JSON.stringify().replace('true', 'True')` because you might have a string with the word "true" in it in the input. You have to write your own `JSON.stringifyAsPython()` function if you want to do it correctly.

**Comment by nilay1221** [comment]
Yes. I wrote the function 

```javascript
function parseJson(jsonObj,indent){
	
	let dataStr = '{\n'
	let len = Object.keys(jsonObj).length;
	let cnt = 0
	for(let key in jsonObj){
		let val = jsonObj[key]
		dataStr += ' '.repeat(indent) + repr(key) + ':'
		switch(typeof val){
			case 'string':
				dataStr += repr(val)
				break;
			case 'number':
				dataStr += val
				break;
			case 'boolean':
				dataStr += val?'True':'False'
				break;
			case 'object':
				if(val === null)
					dataStr += 'None'
				else
					dataStr += parseJson(val,indent + 2)
				break;
		}
		if(cnt === len - 1){
			dataStr += '\n'
		}
		else
			dataStr += ',\n'
		cnt += 1
	}

	dataStr += ' '.repeat(indent - 2) + '}'
	return dataStr;
}
```

What do you think about this ?

**Comment by nilay1221** [comment]
Yup. I wrote this function 
```javascript
function parseJson(jsonObj,indent,arr=false){
	
	let startSymb = arr?'[':'{';
	let endSymb = arr?']':'}';
	let dataStr = startSymb+ '\n'
	let len = Object.keys(jsonObj).length;
	let cnt = 0
	for(let key in jsonObj){
		let val = jsonObj[key]
		dataStr += ' '.repeat(indent) 
		if(!arr)
			dataStr += repr(key) + ':'
		switch(typeof val){
			case 'string':
				dataStr += repr(val)
				break;
			case 'number':
				dataStr += val
				break;
			case 'boolean':
				dataStr += val?'True':'False'
				break;
			case 'object':
				if(val === null)
					dataStr += 'None'
				else if(Array.isArray(val)){
					dataStr += parseJson(val,indent+2,arr=true); 
				}else
					dataStr += parseJson(val,indent + 2)
				break;
		}
		if(cnt === len - 1){
			dataStr += '\n'
		}
		else
			dataStr += ',\n'
		cnt += 1
	}

	dataStr += ' '.repeat(indent - 2) + endSymb
	return dataStr;
}

```
What do you think about this?

**Comment by verhovsky** [comment]
We now convert JSON to Python code. Discussion of the original issue continues at #334
