### ISSUE TITLE
extending to allow -X ? (which file do I start?)

### ISSUE THREAD

**Issue by archywillhe** [curlconverter/curlconverter#308]
e.g.  from https://alpaca.markets/docs/api-documentation/api-v2/

```
curl -X GET \
    -H "APCA-API-KEY-ID: {YOUR_API_KEY_ID}" \
    -H "APCA-API-SECRET-KEY: {YOUR_API_SECRET_KEY}"\
    https://{apiserver_domain}/v2/account
```

doesn't quite get parsed;

I would love to fork & extend it in the parser; which files should I start? thanks!

**Comment by verhovsky** [comment]
Add a " " before the `\`

This was a bug in the bash parser that was fixed but we haven't updated it yet.
