### ISSUE TITLE
Error parsing curl command: expected a 'command' AST node, got redirected_statement instead

### ISSUE THREAD

**Issue by mikegyver99** [curlconverter/curlconverter#316]
`curl -H "X-Requested-With: curl" -H "Content-Type: text/xml" -u "USER:PASS" -X "POST" --data-binary @- "https://example.com/api/2.0/fo/auth/unix/?action=create&title=UnixRecord&username=root&password=abc123&ips=10.10.10.10" < add_params.xml`

**Comment by verhovsky** [comment]
Your command pipes input from a file `< add_params.xml`, if you remove it, it'll convert it to 

```py
import requests

headers = {
    'X-Requested-With': 'curl',
    'Content-Type': 'text/xml',
}

params = (
    ('action', 'create'),
    ('title', 'UnixRecord'),
    ('username', 'root'),
    ('password', 'abc123'),
    ('ips', '10.10.10.10'),
)

data = open('-', 'rb').read()
response = requests.post('https://example.com/api/2.0/fo/auth/unix/', headers=headers, params=params, data=data, auth=('USER', 'PASS'))
```

and then I think you just need to manually change 

```py
data = open('-', 'rb').read()
```

to 

```py
data = open('add_params.xml', 'rb').read()
```

**Comment by mikegyver99** [comment]
Thanks, that manual code edit works.

**Comment by verhovsky** [comment]
You could also edit your command to pass the filename directly to curl:

```
--data-binary @add_params.xml
```

instead of telling it read from stdin and piping the file's contents

```
--data-binary @- < add_params.xml
```

and that gets converted the way you'd expect.
