### ISSUE TITLE
Python: json post data should be formatted as a dict

### ISSUE THREAD

**Issue by NicolasM-Forsk** [curlconverter/curlconverter#326]
Good: 
```
data = {
    "toto": "tata"
}
requests.post(url, json=data)
```

Actual: 
```
data = '{\n  "toto": "tata"\n}\n'
requests.post(url, data=data)
```

**Comment by verhovsky** [comment]
This has already been done https://github.com/curlconverter/curlconverter/pull/318 , it just hasn't been released yet https://github.com/curlconverter/curlconverter.github.io/pull/17
