### ISSUE TITLE
The curl command is correct but can't convert #failure to parse command

### ISSUE THREAD

**Issue by Kevinguo087** [curlconverter/curlconverter#331]
Error parsing curl command:
command should begin with "curl" but instead begins with "curl 'https://lulu.lulufind..."

**Comment by Kevinguo087** [comment]
The curl command 
`curl 'https://lulu.lulufind.com/mrzy/mrzypc/getAchievementDetail'  -H 'Host: lulu.lulufind.com'  -H 'Accept: application/json, text/plain, */*'  -H 'app_version: 1.0.0'  -H 'Accept-Language: zh-CN,zh-Hans;q=0.9'  -H 'Accept-Encoding: gzip, deflate, br'`

**Comment by verhovsky** [comment]
you must be somehow copying some weird whitespace character at the beginning of your command line, because I can paste that command just fine:

```
import requests

headers = {
    'Host': 'lulu.lulufind.com',
    'Accept': 'application/json, text/plain, */*',
    'app_version': '1.0.0',
    'Accept-Language': 'zh-CN,zh-Hans;q=0.9',
    'Accept-Encoding': 'gzip, deflate, br',
}

response = requests.get('https://lulu.lulufind.com/mrzy/mrzypc/getAchievementDetail', headers=headers)
```

**Comment by verhovsky** [comment]
The spaces in your command are [non-breaking space](https://en.wikipedia.org/wiki/Non-breaking_space) characters instead of normal ASCII [spaces](https://en.wikipedia.org/wiki/Space_(punctuation)).

**Comment by Kevinguo087** [comment]
I see, thank you!------------------ Original ------------------From: Boris Verkhovskiy  ***@***.***>Date: Sat,Mar 12,2022 4:49 PMTo: curlconverter/curlconverter ***@***.***>Cc: Kevinguo087 ***@***.***>, Author ***@***.***>Subject: Re: [curlconverter/curlconverter] The curl command is correct butcan't convert #failure to parse command (Issue #331)
The spaces in your command are non-breaking space characters instead of normal ASCII spaces.

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/curlconverter/curlconverter/issues/331#issuecomment-1065843431",
"url": "https://github.com/curlconverter/curlconverter/issues/331#issuecomment-1065843431",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by verhovsky** [comment]
I'm reopening this because I want to replace the whitespace for you on the website

**Comment by Kevinguo087** [comment]
> I'm reopening this because I want to replace the whitespace for you on the website

Wow! Thank you! What can I do for You?

**Comment by verhovsky** [comment]
Keep using the tools and keep reporting any issues you problems you have with is so that we can make it better.

You can also donate to the project's development https://github.com/sponsors/NickCarneiro
