### ISSUE TITLE
Add multipart form support to PHP

### ISSUE THREAD

**Issue by ankitgoyal91** [curlconverter/curlconverter#34]
It's not working. Returning wrong and partial result.
```
curl https://api.sendgrid.com/api/mail.send.json \
-F to=recipient@domain.com -F toname=test -F subject="Example Subject" \
-F text="testing text body" --form-string html="<strong>testing html body</strong>" \
-F from=test@yourdomain.com -F api_user=your_sendgrid_username -F api_key=your_sendgrid_password \
-F files\[attachment.gz\]=@f.php.gz
```

**Comment by NickCarneiro** [comment]
I'm going to wait until `rmccue/requests` gets the ability to pass in file pointers.

https://github.com/rmccue/Requests/milestone/4

If someone else wants to tackle this in the meantime, go for it.

**Comment by verhovsky** [comment]
We switched the PHP generator to output libcurl code and it now supports `-F`

**Comment by verhovsky** [comment]
re-opening because `--form-string` is being ignored
