### ISSUE TITLE
repeated headers are not correctly concatenated

### ISSUE THREAD

**Issue by vlukashov** [curlconverter/curlconverter#359]
When parsing a curl command with repeating headers, like in `curl example.com --header "Accept: application/json" --header "Accept: */*"`, I expect the value for the repeated header to be correctly concatenated like in the snippet ⬇️ but with `curlconverter` 3.21.0 this is not the case.

Expected:
```js
var fetch = require('node-fetch');

fetch('example.com', {
    headers: {
        'Accept': 'application/json,*/*',
    }
});
```

Actual:
```js
var fetch = require('node-fetch');

fetch('example.com', {
    headers: {
        'Accept': 'application/json',
        'Accept': '*/*'
    }
});
```

A relevant excerpt from the HTTP spec with links to the full spec: https://stackoverflow.com/a/24502264

**Comment by verhovsky** [comment]
This is not how curl behaves though. Testing with `nc -kl 8888` and running this command `curl localhost:8888 --header "Accept: application/json" --header "Accept: */*"` we get this output

```
GET / HTTP/1.1
Host: localhost:8888
User-Agent: curl/7.77.0
Accept: application/json
Accept: */*
```

I think it's better to match curl's behavior, the idea being that if a curl command works (i.e. causes the server you're sending requests to to send you the data you want) the converted code will too.

**Comment by vlukashov** [comment]
I agree, it’s better to match the curl behavior. But there is a problem with generating

```js
headers: {
    'Accept': 'application/json',
    'Accept': '*/*'
}
```

The second key/value pair overshadows the first one. Effectively, this leads to a fetch call that ignores the first header.

I have not checked with the other languages / generators, but I’m guessing some of them would have a similar issue.

I would not close this issue just yet.

**Comment by verhovsky** [comment]
You're right, I was in the middle of writing a similar comment to re-open the issue. We have [the same problem](https://github.com/curlconverter/curlconverter/issues/161#issuecomment-1072970913) with the `Cookie` header, which is concatenated but separated by `;`. We need a parser for each header and we'll have to add a comment to warn users that the generated request will be a bit different different.
