### ISSUE TITLE
the `--header "name;"` syntax for headers with no value is not handled correctly

### ISSUE THREAD

**Issue by vlukashov** [curlconverter/curlconverter#360]
When parsing a curl command having a header with no-value, e.g. `curl https://httpbin.org/anything --header "X-Trace-Enabled;"`, I expect the header name to be parsed correctly (without the trailing `;`) but with `curlconverter` 3.21.0 this is not the case.

The relevant part of the curl manual: https://curl.se/docs/manpage.html#-H

Expected:
```js
var fetch = require('node-fetch');

fetch('https://httpbin.org/anything', {
    headers: {
        'X-Trace-Enabled': ''
    }
});
```

Actual:
```js
var fetch = require('node-fetch');

fetch('https://httpbin.org/anything', {
    headers: {
        'X-Trace-Enabled;': ''
    }
});
```

**Comment by verhovsky** [comment]
for reference: we're also going to fix this in Chrome

https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/3543151
