### ISSUE TITLE
curlconverter.toJsonString()报错

### ISSUE THREAD

**Issue by 13593594926** [curlconverter/curlconverter#394]
Parameter 'url' must be a string, not undefined

**Comment by verhovsky** [comment]
curlconverter version?

**Comment by verhovsky** [comment]
I can't help you if all you say is "there is a problem" and post an error message with no explanation. In order to help solve your problem I need to be able to also experience the issue, please post the steps I can take to also get the same error message next time you report a problem.

> (google translate)
> 如果您只说“有问题”并发布错误消息而没有任何解释，我无法帮助您。 为了帮助解决您的问题，我也需要能够遇到该问题，请发布我可以采取的步骤，以便在您下次报告问题时也收到相同的错误消息。
