### ISSUE TITLE
Can provide the docker image of this conversion tool?

### ISSUE THREAD

**Issue by sirliu** [curlconverter/curlconverter#401]
This conversion tool is the best I have found on the Internet, But due to network reasons, access from me will be very slow. I hope it can be deployed locally. Can you provide a Docker image? 
I don’t know anything about the front end, otherwise I just write Dockerfiles myself, or can provide deployment steps, I can write Dockerfiles according to the deployment steps. 
Thanks!

**Comment by verhovsky** [comment]
The website doesn't need an internet connection to work. If load it and then just leave the tab open, it'll work regardless of what your internet connection is like.

The instructions on how to build the site are in the sites repo's readme

https://github.com/curlconverter/curlconverter.github.io

They are

```sh
git clone https://github.com/curlconverter/curlconverter.github.io.git
cd curlconverter.github.io.git
npm install # this requires docker to be running
npm start
```

Or `npm build` instead then you whatever you want to host the dist/ directory, like `cd dist; python -m http.server`

**Comment by sirliu** [comment]
Thank for reply,It's very kind of you!

**Comment by sirliu** [comment]
Anyone want deploy this web tool by Docker:
## creat dockerfile first 
```Dockerfile
FROM nginx:stable-alpine
COPY ./curlconverter.github.io-gh-pages /usr/share/nginx/html
```
```
FROM arm64v8/nginx:stable-alpine
COPY ./curlconverter.github.io-gh-pages /usr/share/nginx/html
```
## second
```
wget https://github.com/curlconverter/curlconverter.github.io/archive/refs/heads/gh-pages.zip
unzip gh-pages.zip
docker build -t curlconverter:latest .
docker build -f Arm64Dockerfile -t curlconverter:arm64 .
```
## last run
`docker run -itd --name=curlconverter -p 80:80 curlconverter:latest

See the detail at:https://github.com/sirliu/curlconverter
