### ISSUE TITLE
CFML tab dissapeared

### ISSUE THREAD

**Issue by scottsteinbeck** [curlconverter/curlconverter#416]
Somehow the CFML tab is no longer on the curlconverter.com website. It used to be there, can it be brought back? If there is something it is missing and needs to be updated, let me know, I am the author of the CFML conversion.

![Screen Shot 2022-07-12 at 9 50 45 AM](https://user-images.githubusercontent.com/5215594/178548872-def1fb7d-7a50-43fb-9b9f-2539c146b795.png)

**Comment by dave-at-goss** [comment]
+1 functionality is missed
