### ISSUE TITLE
Unable to Install the Package - gyp ERR! find Python

### ISSUE THREAD

**Issue by petermarks12** [curlconverter/curlconverter#436]
I am using Node v16.17.0 and every time I try to install the package, I am getting the following error. Do I need to install python?

> npm ERR! path D:\my-app\node_modules\@curlconverter\tree-sitter-bash
> npm ERR! command failed
> npm ERR! command C:\Windows\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild
> npm ERR! prebuild-install warn install No prebuilt binaries found (target=16.17.0 runtime=node arch=x64 libc= platform=win32)
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@9.0.0
> npm ERR! gyp info using node@16.17.0 | win32 | x64
> npm ERR! gyp ERR! find Python

**Comment by verhovsky** [comment]
Are you doing

```
npm install curlconverter
```

or 

```
git clone https://github.com/curlconverter/curlconverter
cd curlconverter
npm install
```

? If it's the latter, then you need to have Docker running.

**Comment by Penggeor** [comment]
Encounter the same problem, but I can install package when I use v16.15.1(lts/gallium) but can't when using lastest version(17.9.0).

**Comment by lerman01** [comment]
+1

**Comment by OneOnlineShow** [comment]
+1

**Comment by verhovsky** [comment]
To answer the question, yes if there's no pre-built binary for your system you will need node-gyp and Python to build it. This was an oversight, we were prebuilding one of the dependencies but not the other one. But this should be fixed now, let me know if you still see this error with v4.7.1.
