### ISSUE TITLE
Error: "TypeError: Cannot read properties of undefined (reading 'charAt')"

### ISSUE THREAD

**Issue by Firdavs-coder** [curlconverter/curlconverter#438]
**Input**:

```sh
curl -v -X POST "http://api-soft.photolab.me/template_process.php" \
    -F image_url[1]=http://soft.photolab.me/samples/girl.jpg \
    -F aylantirish [1]=0 \
    -F flip[1]=0 \
    -F kesish[1]=0,0,1,1 \
    -F template_name="2765"
```

**Expected output**:

**Comment by verhovsky** [comment]
You have a extra space here

```
    -F aylantirish [1]=0 \
```

Which makes it error when it tries to parse `aylantrish` as a `-F` value, because those should always contain a `=`.

Try adding quotes

```sh
curl -v -X POST "http://api-soft.photolab.me/template_process.php" \
    -F image_url[1]=http://soft.photolab.me/samples/girl.jpg \
    -F 'aylantirish [1]=0' \
    -F flip[1]=0 \
    -F kesish[1]=0,0,1,1 \
    -F template_name="2765"
```

This error message will be improved in #437

**Comment by Firdavs-coder** [comment]
> You have an extra space here
> 
> ```
>     -F aylantirish [1]=0 \
> ```
> 
> which makes it error when it tries to parse `aylantrish` as a `-F` value, because those should always contain a `=`.
> 
> Try adding quotes
> 
> ```shell
> curl -v -X POST "http://api-soft.photolab.me/template_process.php" \
>     -F image_url[1]=http://soft.photolab.me/samples/girl.jpg \
>     -F 'aylantirish [1]=0' \
>     -F flip[1]=0 \
>     -F kesish[1]=0,0,1,1 \
>     -F template_name="2765"
> ```
> 
> This error message will be improved in #437

Thank you

**Comment by Firdavs-coder** [comment]
Thank you. It works
