### ISSUE TITLE
Error: "Error: option --headercustomerCode: myCustomerCode: is unknown"

### ISSUE THREAD

**Issue by mmann01** [curlconverter/curlconverter#446]
**Input**:

```sh
curl --user myLogin:myPassword --header"customerCode: myCustomerCode" --header"Accept: application/json" --get https://cleartrial-api.oracleindustry.com/cleartrial-ws/plans/10801/locations

```

**Expected output**:

This syntax is directly from oracle docs: https://docs.oracle.com/en/industries/health-sciences/cleartrial-cloud/api-guide/requirements-working-api.html#GUID-32CD26A9-4486-443E-9F27-DE646DA8885B

**Comment by verhovsky** [comment]
Have you tried running this command, curl will give you the same error? You need a space after `--header`.

**Comment by mmann01** [comment]
That solved it, I didn't catch that before. Thank you
________________________________
From: Boris Verkhovskiy ***@***.***>
Sent: Wednesday, September 7, 2022 4:44:45 PM
To: curlconverter/curlconverter ***@***.***>
Cc: Mikeal Mann ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [curlconverter/curlconverter] Error: "Error: option --headercustomerCode: myCustomerCode: is unknown" (Issue #446)


Have you tried running this command, curl will give you the same error? You need a space after --header.
