### ISSUE TITLE
Parse multipart/form-data in --data

### ISSUE THREAD

**Issue by adw3r** [curlconverter/curlconverter#457]
![image](https://user-images.githubusercontent.com/77853696/197512718-e395151e-7da1-411d-b4b7-9d0f2fad9acb.png)

![image](https://user-images.githubusercontent.com/77853696/197512781-12ca3283-9efb-47ca-afe6-1f37c913c4ce.png)

Multipart-form data converts into {'data' : {'key': ''}} pair where 'key' is actual data string of a request. In python, for example, it converts into data = 'key' string.

**Comment by alexeyNaidiuk** [comment]
curl 'https://sgg.ae/wp-json/contact-form-7/v1/contact-forms/295/feedback' \
  -H 'authority: sgg.ae' \
  -H 'accept: application/json, text/javascript, */*; q=0.01' \
  -H 'accept-language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundaryXSzdE07OT2MkeOO7' \
  -H 'cookie: pll_language=en' \
  -H 'origin: https://sgg.ae' \
  -H 'referer: https://sgg.ae/contact-us/' \
  -H 'sec-ch-ua: "Chromium";v="106", "Google Chrome";v="106", "Not;A=Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36' \
  -H 'x-requested-with: XMLHttpRequest' \
  --data-raw $'------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name="_wpcf7"\r\n\r\n295\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name="_wpcf7_version"\r\n\r\n5.1.4\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name="_wpcf7_locale"\r\n\r\nen_US\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name="_wpcf7_unit_tag"\r\n\r\nwpcf7-f295-o1\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name="_wpcf7_container_post"\r\n\r\n0\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name="your-name"\r\n\r\ntest\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name="your-email"\r\n\r\nsoftumwork@gmail.com\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name="your-subject"\r\n\r\ntest\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name="your-message"\r\n\r\ntest\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name="send_c[]"\r\n\r\nSend copy to yourself\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7--\r\n' \
  --compressed


you can use this CURL example as a test data

**Comment by verhovsky** [comment]
The issue here is really that Chrome's "Copy as cURL" doesn't parse `multipart/form-data` data into curl's native `-F` arguments. Even the curl documentation specifically calls out this limitation:

https://everything.curl.dev/usingcurl/copyas#not-perfect

Your command (I've simplified and converted it to `http://localhost:8888` so that we can see what it sends using `nc -kl 8888`):

```sh
curl 'http://localhost:8888' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundaryXSzdE07OT2MkeOO7' \
  --data-raw $'------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name="_wpcf7"\r\n\r\n295\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name="_wpcf7_version"\r\n\r\n5.1.4\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name="_wpcf7_locale"\r\n\r\nen_US\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name="_wpcf7_unit_tag"\r\n\r\nwpcf7-f295-o1\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name="_wpcf7_container_post"\r\n\r\n0\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name="your-name"\r\n\r\ntest\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name="your-email"\r\n\r\nsoftumwork@gmail.com\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name="your-subject"\r\n\r\ntest\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name="your-message"\r\n\r\ntest\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name="send_c[]"\r\n\r\nSend copy to yourself\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7--\r\n'
```

sends this body:

```
------WebKitFormBoundaryXSzdE07OT2MkeOO7
Content-Disposition: form-data; name="_wpcf7"

295
------WebKitFormBoundaryXSzdE07OT2MkeOO7
Content-Disposition: form-data; name="_wpcf7_version"

5.1.4
------WebKitFormBoundaryXSzdE07OT2MkeOO7
Content-Disposition: form-data; name="_wpcf7_locale"

en_US
------WebKitFormBoundaryXSzdE07OT2MkeOO7
Content-Disposition: form-data; name="_wpcf7_unit_tag"

wpcf7-f295-o1
------WebKitFormBoundaryXSzdE07OT2MkeOO7
Content-Disposition: form-data; name="_wpcf7_container_post"

0
------WebKitFormBoundaryXSzdE07OT2MkeOO7
Content-Disposition: form-data; name="your-name"

test
------WebKitFormBoundaryXSzdE07OT2MkeOO7
Content-Disposition: form-data; name="your-email"

softumwork@gmail.com
------WebKitFormBoundaryXSzdE07OT2MkeOO7
Content-Disposition: form-data; name="your-subject"

test
------WebKitFormBoundaryXSzdE07OT2MkeOO7
Content-Disposition: form-data; name="your-message"

test
------WebKitFormBoundaryXSzdE07OT2MkeOO7
Content-Disposition: form-data; name="send_c[]"

Send copy to yourself
------WebKitFormBoundaryXSzdE07OT2MkeOO7--
```

This can/should be done using curl's `-F` option like this

```sh
curl 'https://sgg.ae/wp-json/contact-form-7/v1/contact-forms/295/feedback' \
  # -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundaryXSzdE07OT2MkeOO7' \
  -F "_wpcf7=295" \
  -F "_wpcf7_version=5.1.4" \
  -F "_wpcf7_locale=en_US" \
  -F "_wpcf7_unit_tag=wpcf7-f295-o1" \
  -F "_wpcf7_container_post=0" \
  -F "your-name=test" \
  -F "your-email=softumwork@gmail.com" \
  -F "your-subject=test" \
  -F "your-message=test" \
  -F "send_c[]=Send copy to yourself" \
  --compressed
```

We already handle `-F`. That command becomes this JSON

```
    ...
    "data": {
        "_wpcf7": "295",
        "_wpcf7_version": "5.1.4",
        "_wpcf7_locale": "en_US",
        "_wpcf7_unit_tag": "wpcf7-f295-o1",
        "_wpcf7_container_post": "0",
        "your-name": "test",
        "your-email": "softumwork@gmail.com",
        "your-subject": "test",
        "your-message": "test",
        "send_c[]": "Send copy to yourself"
    }
    ...
```

and generated Python code uses the `files=` argument.

The better way to fix this situation would be to contribute to Chrome's DevTools a thing that tries to parse `multipart/form-data` and convert it into the `-F` option. The devtools codebase even has a class for parsing form-data already:



but it's not lossless.

You might've noticed that I commented out the `-H` line in my alternative command, that's because it's actually not equivalent. curl generates its own `boundary` instead of using the `----WebKitFormBoundaryXSzdE07OT2MkeOO7` boundary in the `-H` argument and it actually sends this header

```
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryXSzdE07OT2MkeOO7; boundary=------------------------fe8919be6532dc6b
```

and then uses `--------------------------fe8919be6532dc6b` to separate the data. So actually there's no way for "Copy as cURL" to convert multipart/form-data requests into curl's `-F` option if you care about keeping the same boundary, you have to use `--data`.

Since doing this in "Copy as cURL" would writing code for parsing multipart/form-data content bodies, we might as well add it to curlconverter too.

**Comment by adw3r** [comment]
Проблема несколько другая. Даже с таким превращением формы в json "data": "------WebKitFormBoundaryXSzdE07OT2MkeOO7......" есть проблема. Json объект получается следующий
{
"data": {
     "------WebKitFormBoundaryXSzdE07OT2MkeOO7...": ""
    },
}

**Comment by adw3r** [comment]
{
    "url": "https://sgg.ae/wp-json/contact-form-7/v1/contact-forms/295/feedback",
    "raw_url": "https://sgg.ae/wp-json/contact-form-7/v1/contact-forms/295/feedback",
    "method": "post",
    "cookies": {
        "pll_language": "en"
    },
    "headers": {
        "authority": "sgg.ae",
        "accept": "application/json, text/javascript, */*; q=0.01",
        "accept-language": "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7",
        "content-type": "multipart/form-data; boundary=----WebKitFormBoundaryXSzdE07OT2MkeOO7",
        "cookie": "pll_language=en",
        "origin": "https://sgg.ae",
        "referer": "https://sgg.ae/contact-us/",
        "sec-ch-ua": "\"Chromium\";v=\"106\", \"Google Chrome\";v=\"106\", \"Not;A=Brand\";v=\"99\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\"",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36",
        "x-requested-with": "XMLHttpRequest"
    },
    "data": {
        "------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name=\"_wpcf7\"\r\n\r\n295\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name=\"_wpcf7_version\"\r\n\r\n5.1.4\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name=\"_wpcf7_locale\"\r\n\r\nen_US\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name=\"_wpcf7_unit_tag\"\r\n\r\nwpcf7-f295-o1\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name=\"_wpcf7_container_post\"\r\n\r\n0\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name=\"your-name\"\r\n\r\ntest\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name=\"your-email\"\r\n\r\nsoftumwork@gmail.com\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name=\"your-subject\"\r\n\r\ntest\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name=\"your-message\"\r\n\r\ntest\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7\r\nContent-Disposition: form-data; name=\"send_c[]\"\r\n\r\nSend copy to yourself\r\n------WebKitFormBoundaryXSzdE07OT2MkeOO7--\r\n": ""
    },
    "compressed": true
}

**Comment by verhovsky** [comment]
> Проблема несколько другая

Тут две проблемы. Первая, мне более интересная, которую я описал. Мы можем получить multipart/form-data в одной строке в `--data` которую нужно парсить.

Вторая,  это как правильно преобразовать `--form` в JSON. https://curlconverter.com/json/ это не стандартный формат, когда его добавили там подразумевалось что `"data":` будет использоваться для `application/x-www-form-urlencoded`. То есть

```sh
curl localhost:8888 --data 'foo=bar' --data 'baz=two'
```

->

```http
POST / HTTP/1.1
Host: localhost:8888
User-Agent: curl/8.0.1
Accept: */*
Content-Length: 15
Content-Type: application/x-www-form-urlencoded

foo=bar&baz=two
```

-> 

```
{
    // [...]
    "data": {
        "foo": "bar",
        "baz": "two"
    }
}
```

Теперь первый вопрос, как выразить данные которые нельзя преобразовать в dictionary? Например

```sh
curl localhost:8888 --data 'foo=bar' --data 'baz=two' --data 'foo=repeated'
```

-> 

```http
POST / HTTP/1.1
Host: localhost:8888
User-Agent: curl/8.0.1
Accept: */*
Content-Type: application/x-www-form-urlencoded
Content-Length: 28

foo=bar&baz=two&foo=repeated
```

в данном случае мы просто теряем первое значение `foo`

->

```json
    "data": {
        "foo": "repeated",
        "baz": "two"
    }
```

Но можно например поменять dictionary на список

```json
    "data": [
        ["foo", "bar"],
        ["baz", "two"],
        ["foo", "repeated"]
    ]
```

или вставить всё как один ключ с пустым значением

```json
    "data": {
        "foo=bar&baz=two&foo=repeated": ""
    }
```

тогда если Вы пользуйтесь `"data":` вот так

```js
const originalData = Object.entries(result['data']).map(e => e[0] + '=' + 'e1').join('&')
```

то тогда будет немного не правильно,

```
foo=bar&baz=two&foo=repeated    // оригинал
foo=bar&baz=two&foo=repeated=   // originalData
```

но вроде дополнительное `=` лучше чем потерянное значение...

С вашей командой тоже самое, её нельзя преобразовать в dictionary потому-что в `--data` нету `=`. Можно в таких случаях поменять тип на просто одну строку

```json
    "data": "foo=bar&baz=two&foo=repeated"
```

тогда все должны будут проверять тип

```js
const originalData = typeof result['data'] === "string" ? result['data'] : Object.entries(result['data']).map(e => e[0] + '=' + 'e1').join('&')
```
