### ISSUE TITLE
import_url.default.parse is not a function

### ISSUE THREAD

**Issue by 13593594926** [curlconverter/curlconverter#464]
import_url.default.parse is not a function

**Comment by verhovsky** [comment]
What do you expect me to do with this sentence?

**Comment by verhovsky** [comment]
The issue might be that you need to install `url` and `path-browserify`

https://github.com/curlconverter/curlconverter.github.io/blob/2e1722891be22b1bb5c47976fb7873f6eb86b94d/package.json#L23-L25

and add them and `fs` to your Webpack config:

https://github.com/curlconverter/curlconverter.github.io/blob/2e1722891be22b1bb5c47976fb7873f6eb86b94d/webpack.config.js#L118-L120
