### ISSUE TITLE
Have an option to generate kwargs for requests

### ISSUE THREAD

**Issue by kootenpv** [curlconverter/curlconverter#465]
Nice website!

Basically I'd like it if there was a way to generate the curl as data in Python:

```python
curl_in_python = {
    "method": "GET",
    "url": "https://example.com",
    "headers": {"a": 1},
    "cookies": {"b": 2},
    "params": ...   
}
```

So that basically given that I've set up:

```python
import requests
session = requests.Session()
```

I can always just use:

```python
response = session.request(**curl_in_python)
```

to execute any request produced by curlconverter

(instead that the code always produces `import requests`)

**Comment by verhovsky** [comment]
https://curlconverter.com/json/ might help you here.

**Comment by kootenpv** [comment]
Fantastic, thanks!
