### ISSUE TITLE
command that contains characters escaped with backslash isn't translated properly

### ISSUE THREAD

**Issue by fireattack** [curlconverter/curlconverter#493]
```
ubuntu@peachy:~$ curl -X GET 'https://httpbin.org/get?q=\[GET\]'
{
  "args": {
    "q": "[GET]"
  },
  "headers": {
    "Accept": "*/*",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.81.0",
    "X-Amzn-Trace-Id": "***"
  },
  "origin": "***",
  "url": "https://httpbin.org/get?q=[GET]"
}
ubuntu@peachy:~$
```

Server receives proper q=`[GET]`.

curlconverter converts it to (in Python, for example)
```py
import requests

response = requests.get('https://httpbin.org/get?q=\\[GET\\]')

```

which instead is using `\[GET\]` as query parameter:

```
> print(response.json()['args']['q'])
\[GET\]
```

**Comment by verhovsky** [comment]
This has to do with curl's URL globbing syntax. You can tell curl to query 10 urls like this

```sh
curl http://example.com/file_[1..10].jpg
```

so if you want to query the literal url "`http://example.com/file_[1..10].jpg`", curl lets you backslash-escape the square brackets:

```sh
http://example.com/file_\[1..10\].jpg
```

Fixing this means re-implementing curl's URL globbing, at least partially. Thank you for the report.
