### ISSUE TITLE
Add Got library support for Node.js

### ISSUE THREAD

**Issue by koalex** [curlconverter/curlconverter#494]
It will be great to add [Got](https://github.com/sindresorhus/got) library for Node.js

**Comment by koalex** [comment]
It will be great to add [Got](https://github.com/sindresorhus/got) library for Node.js

**Comment by verhovsky** [comment]
And ky, and simple-get and superagent

https://npmtrends.com/axios-vs-got-vs-ky-vs-node-fetch-vs-request-vs-simple-get-vs-superagent

**Comment by koalex** [comment]
Thanks!
