### ISSUE TITLE
Do not set 'Content-Type' for Python

### ISSUE THREAD

**Issue by viralsword** [curlconverter/curlconverter#52]
Setting 'Content-Type', causing problem in Python 'request', if "Content-Type" is set requests is not sending 'boundry' in the header.

This is creating problem in accepting 'multipart-form'.

**Comment by NickCarneiro** [comment]
Thanks for finding this bug. I'm including some information for myself below.

Example command:
`curl http://localhost:3001 -H "Authorization: Bearer ACCESS_TOKEN" -X POST -F attributes='{"name":"tigers.jpeg", "parent":{"id":"11446498"}}' -F file=@myfile.jpg -H "Content-Type: multipart/form-data"`

A multipart form must have a boundary defined. Curl generates a new boundary for every request.
![correct_boundary_from_curl](https://user-images.githubusercontent.com/700209/30818635-ea376b80-a1d0-11e7-8636-08d641fedb6e.png)

**Comment by verhovsky** [comment]
Discussion continues at #248
