### ISSUE TITLE
Web version does not display header "Content-Type" (curl to python)

### ISSUE THREAD

**Issue by vovavovavovavova** [curlconverter/curlconverter#533]
Converting Curl to python requests
14.03.2023

Missing "Content-Type" header, in python result. I checked this header in curl pasting, it exists.
```-H 'content-type: application/x-www-form-urlencoded' -H 'user-agent: Mozilla/5.0...```

Previously it was ok and header displayed correcttly.

**Comment by verhovsky** [comment]
It's deleted when it becomes redundant, Requests will add that header with that value when you include a `data=` argument.

**Comment by vovavovavovavova** [comment]
it's not redundant, if I emulate request with python without for example urlencoded header, using the output of CurlConverter (where data is an javascript object / python dict), it will be a bit different request!

**Comment by verhovsky** [comment]
Can you give me an example command?

**Comment by vovavovavovavova** [comment]
cut command
`curl -H 'Host: xxx' -H 'content-type: application/x-www-form-urlencoded' --data-binary "action=past&type=1" --compressed 'https://mysite/endpoint'`

will be converted and displayed at web interface as

```import requests

headers = {
    'Host': 'xxx',
}

data = {
    'action': 'past',
    'type': '1',
}

response = requests.post('https://mysite/endpoint', headers=headers, data=data)```

**Comment by verhovsky** [comment]
Thank you. We can start a simple server on port 8888 with `nc -kl 8888` and send this request with curl to it:

```sh
curl -H 'Host: xxx' -H 'content-type: application/x-www-form-urlencoded' --data-binary "action=past&type=1" --compressed 'http://localhost:8888/endpoint'
```

and see that curl sends this HTTP:

```
POST /endpoint HTTP/1.1
Host: xxx
User-Agent: curl/7.88.1
Accept: */*
Accept-Encoding: deflate, gzip, br, zstd
content-type: application/x-www-form-urlencoded
Content-Length: 18

action=past&type=1
```

If we run the Python code that that command is converted to, we get this HTTP

```
POST /endpoint HTTP/1.1
User-Agent: python-requests/2.28.1
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Host: xxx
Content-Length: 18
Content-Type: application/x-www-form-urlencoded
```

The curl command sends `content-type: application/x-www-form-urlencoded` and the Python code sends `Content-Type: application/x-www-form-urlencoded`

**Comment by verhovsky** [comment]
I changed it to only remove the redundant content-type header if it's the only header. https://github.com/curlconverter/curlconverter/commit/7548d4ca47c6d060d43560167053ec77aea65625

**Comment by vovavovavovavova** [comment]
my request had a lot more headers, that was just a stripped example.

But if it is correctly added by requests by default, then it is not an issue.
