### ISSUE TITLE
--upload-file

### ISSUE THREAD

**Issue by zladuric** [curlconverter/curlconverter#55]

**Comment by zladuric** [comment]
Hey, just saw that this awesomeness is missing the --upload-file option for Node.js.
This:
    curl http://localhost  --upload-file file.txt 
gives this:
    var request = require('request');
    var options = {
      url: 'http://localhost'
    };
    function callback(error, response, body) {
      if (!error && response.statusCode == 200) {
        console.log(body);
      }
    }
    request(options, callback);

It would probably be simple to add something like:

    var options = {
      url: 'http://localhost',
      body: require('fs').readFileSync('file.txt.'),
    }

Thought I might it here.

**Comment by NickCarneiro** [comment]
Thanks for the example. The node output has sadly not gotten enough attention.

**Comment by wotanii** [comment]
same problem with python. `--upload-file` seems to be ignored in general

**Comment by verhovsky** [comment]
the JS `fetch()` and Python generators now support `--upload-file`. Since `request` is deprecated now, I'm not going to improve it so I'm going to call this issue done.
