### ISSUE TITLE
Tried a curl  command and an error about "curl" not starting the command popped up

### ISSUE THREAD

**Issue by Kostas-Mavrogalos** [curlconverter/curlconverter#581]
I found [this](https://www.mail-archive.com/adwords-api@googlegroups.com/msg96717.html) answer from somewhere and copy-pasted the cURL command in the convertor, and 
![this](https://github.com/curlconverter/curlconverter/assets/60011593/34fd67e6-d1f4-4083-8779-320e6490d656)
error popped up.
Just thought I should mention it

**Comment by Kostas-Mavrogalos** [comment]
Apparently, it had something to do with the EOL characters involved. When I deleted all the EOL characters that were in between each line, the convertor operated as expected.
I will leave this issue open just in case you want to investigate.

**Comment by verhovsky** [comment]
It's because you have extra newlines between your command. If you paste this into bash

```sh
curl --data "grant_type=refresh_token" \

  --data "client id=CLIENT ID" \

  --data "client secret=CLIENT SECRET" \

  --data "refresh token=REFRESH TOKEN" \
```

 it'll give you a similar "--data" is not a command error. If you remove the extra newlines, it'll work

```sh
curl --data "grant_type=refresh_token" \
  --data "client id=CLIENT ID" \
  --data "client secret=CLIENT SECRET" \
  --data "refresh token=REFRESH TOKEN" \
```

If you have any suggestions for how to improve the error message to make this clearer, let me know.

**Comment by Kostas-Mavrogalos** [comment]
I would prefer it if it said something along the lines of:"Too many new line characters are present. Remove some or make the command one line", so that people would more easily understand why that happened. I, fortunately, got why the error message popped up, but others might not be as lucky.
