### ISSUE TITLE
Its not work for me, please help me

### ISSUE THREAD

**Issue by jonas9881** [curlconverter/curlconverter#586]
Hi, i try with this https://lic.drmtoday.com/license-proxy-widevine/cenc/?specConform=true&assetId=tvmedia-20468562
but dont work and this https://playback2.a2d.tv/play/8eec9e7663917ec29a89?service=tv4play&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome&capabilities=live-drm-adstitch-2%2Cyospace3
But dont work this either, so can anyone help me to download a serie . i found this info here: https://github.com/medvm/widevine_keys and the picture here https://user-images.githubusercontent.com/43696206/145660715-472e4c65-86de-453f-86fc-5bb14028f448.png

Please help me.

**Comment by verhovsky** [comment]
Sorry, I can't help you with this

https://www.law.cornell.edu/uscode/text/17/1201
