### ISSUE TITLE
CURLFile is not correct !

### ISSUE THREAD

**Issue by typeoo** [curlconverter/curlconverter#593]
curl_setopt($ch, CURLOPT_POSTFIELDS, [
    'file' => new CURLFile('test.mp3;type=audio/mpeg'),
]);

it should be like:

curl_setopt($ch, CURLOPT_POSTFIELDS, [
    'file' => new CURLFile('/var/www/html/voice/test.mp3',"audio/mpeg","test")
]);

**Comment by verhovsky** [comment]
#217
