### ISSUE TITLE
Support for multiline curl commands?

### ISSUE THREAD

**Issue by daddy32** [curlconverter/curlconverter#598]
Sometimes, for the sake of the readability, we split the `curl` command into multiple lines:
Linux format:
```bash
curl --request POST \
  --url https://www.example.com \
  --header "Content-Type: application/x-www-form-urlencoded" \
...
```
Windows format:
```powershell
curl --request POST ^
  --url https://www.example.com ^
  --header "Content-Type: application/x-www-form-urlencoded" ^
...
```

This tool does not like that :)
```
Error: command should begin with "curl" but instead begins with "--url"
```

I'm not sure if this is in the scope of the project, but if it aims to support generic `curl` format, then it also includes this.

**Comment by verhovsky** [comment]
This is already supported, try pasting your linux example into the tool. Your issue is that "windows format" is not supported, see #143

**Comment by daddy32** [comment]
I would swear I got the error for Linux syntax too, but can't reproduce it now. So: OK.
