### ISSUE TITLE
Curl Convert - Catarse

### ISSUE THREAD

**Issue by Rafa-Mariano** [curlconverter/curlconverter#613]
curl "https://api.catarse.me/user_details?id=eq.1089042" ^
  -H "authority: api.catarse.me" ^
  -H "accept: application/json, text/*" ^
  -H "accept-language: pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7" ^
  -H "origin: https://www.catarse.me" ^
  -H "prefer: count=none" ^
  -H "range: 0-0" ^
  -H "range-unit: items" ^
  -H "referer: https://www.catarse.me/" ^
  -H "sec-ch-ua: ^\^"Not_A Brand^\^";v=^\^"8^\^", ^\^"Chromium^\^";v=^\^"120^\^", ^\^"Google Chrome^\^";v=^\^"120^\^"" ^
  -H "sec-ch-ua-mobile: ?0" ^
  -H "sec-ch-ua-platform: ^\^"Windows^\^"" ^
  -H "sec-fetch-dest: empty" ^
  -H "sec-fetch-mode: cors" ^
  -H "sec-fetch-site: same-site" ^
  -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" ^
  --compressed

**Comment by verhovsky** [comment]
Click "copy as curl (bash)" instead of "copy as curl (cmd)"

#143
