### ISSUE TITLE
npm module cannot convert to json correctly

### ISSUE THREAD

**Issue by pp90opk** [curlconverter/curlconverter#622]
with curl command:
```sh
curl   -H "Content-Type: application/json; charset=UTF-8" --data-binary "{\"sd\":\"MYVNhQFgtEQ8kwIMXEs=\"}" --compressed "https://event.tatistics"
```

the webpage converts it correctly, but with nodejs, it parses data wrongly:
result with nodejs
```js
{
  url: 'https://event.tatistics',
  raw_url: 'https://event.tatistics',
  method: 'post',
  headers: { 'Content-Type': 'application/json; charset=UTF-8' },
  data: '{sd:MYVNhQFgtEQ8kwIMXEs=}',
  compressed: true
}
```
result with webpage:
```json
{
    "url": "https://event.tatistics",
    "raw_url": "https://event.tatistics",
    "method": "post",
    "headers": {
        "Content-Type": "application/json; charset=UTF-8"
    },
    "data": {
        "sd": "MYVNhQFgtEQ8kwIMXEs="
    },
    "compressed": true
}
```

and my nodejs code:
```js
let req = JSON.parse(curlconverter.toJsonString(curl))
        console.log(req)
```

**Comment by verhovsky** [comment]
That is correct. You're doing `JSON.parse()` which is parsing the JSON into a JavaScript object then you're logging the JavaScript object. If you want to log the JSON, change your code to

```js
let req = curlconverter.toJsonString(curl)
console.log(req)
```

or if you want to parse the JSON and then turn into a nice JSON again

```js
let req = JSON.parse(curlconverter.toJsonString(curl))
console.log(JSON.stringify(req))
```

or if you want it to look nicer

```js
let req = JSON.parse(curlconverter.toJsonString(curl))
console.log(JSON.stringify(req, null, "    "))
```

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

**Comment by pp90opk** [comment]
the curl command is copied directly from proxy tool charles, from its Copy Curl Request function, and converted  directly without changing anything. in this case, the data would not be parsed correctly as a valid json object.

**Comment by verhovsky** [comment]
When you convert a bash command into a JavaScript string, you need to respect JavaScript syntax, otherwise you're causing it to be parsed incorrectly.
