### ISSUE TITLE
curlConverter for React

### ISSUE THREAD

**Issue by BhojrajPathak001** [curlconverter/curlconverter#623]
I am getting this erros when i try to import 
import * as curConverter from 'curlconverter'

ERROR in ./node_modules/web-tree-sitter/tree-sitter.js 38:21-34
Module not found: Error: Can't resolve 'fs' in 'C:\Users\bhojraj pathak\Desktop\abcd\curlconverter\node_modules\web-tree-sitter'

ERROR in ./node_modules/web-tree-sitter/tree-sitter.js 39:25-40
Module not found: Error: Can't resolve 'path' in 'C:\Users\bhojraj pathak\Desktop\abcd\curlconverter\node_modules\web-tree-sitter'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }

ERROR in ./node_modules/yamljs/lib/Utils.js 250:11-20
Module not found: Error: Can't resolve 'fs' in 'C:\Users\bhojraj pathak\Desktop\abcd\curlconverter\node_modules\yamljs\lib'

**Comment by verhovsky** [comment]
Please take a look at the webpack.config.js for curlconverter.com

https://github.com/curlconverter/curlconverter.github.io/blob/master/webpack.config.js

Specifically, you'll need these lines

https://github.com/curlconverter/curlconverter.github.io/blob/25440e4361ab53fa845b586e086b653d6f4f5efa/webpack.config.js#L122-L133

and to install them

https://github.com/curlconverter/curlconverter.github.io/blob/25440e4361ab53fa845b586e086b653d6f4f5efa/package.json#L17-L31
