### ISSUE TITLE
Unable to install in the Python 3.12

### ISSUE THREAD

**Issue by edisonyan** [curlconverter/curlconverter#628]
> node_modules/.pnpm/tree-sitter@0.20.6/node_modules/tree-sitter: Running install script...
> node_modules/.pnpm/@curlconverter+tree-sitter-bash@0.0.3/node_modules/@curlconverter/tree-sitter-bash: Running install script, failed in 13.6s
> .../@curlconverter/tree-sitter-bash install$ prebuild-install || node-gyp rebuild
> │ prebuild-install warn install Request timed out
> │ C:\dev\zt-autotestweb\node_modules\.pnpm\@curlconverter+tree-sitter-bash@0.0.3\node_modules\@curlconverter\tree-sitter-bash>if not defined npm_config_node_gyp (node "C:\Users\Administrator\AppData\Roami…  
> │ gyp info it worked if it ends with ok
> │ gyp info using node-gyp@9.4.0
> │ gyp info using node@20.9.0 | win32 | x64
> │ gyp info find Python using Python version 3.12.0 found at "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\python.exe"
> │ gyp info find VS using VS2022 (17.3.32929.385) found at:
> │ gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
> │ gyp info find VS run with --verbose for detailed information
> │ gyp info spawn C:\Users\Administrator\AppData\Local\Programs\Python\Python312\python.exe
> │ gyp info spawn args [
> │ gyp info spawn args   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\gyp\\gyp_main.py',
> │ gyp info spawn args   'binding.gyp',
> │ gyp info spawn args   '-f',
> │ gyp info spawn args   'msvs',
> │ gyp info spawn args   '-I',
> │ gyp info spawn args   'C:\\dev\\zt-autotestweb\\node_modules\\.pnpm\\@curlconverter+tree-sitter-bash@0.0.3\\node_modules\\@curlconverter\\tree-sitter-bash\\build\\config.gypi',
> │ gyp info spawn args   '-I',
> │ gyp info spawn args   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\addon.gypi',
> │ gyp info spawn args   '-I',
> │ gyp info spawn args   'C:\\Users\\Administrator\\AppData\\Local\\node-gyp\\Cache\\20.9.0\\include\\node\\common.gypi',
> │ gyp info spawn args   '-Dlibrary=shared_library',
> │ gyp info spawn args   '-Dvisibility=default',
> │ gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator\\AppData\\Local\\node-gyp\\Cache\\20.9.0',
> │ gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\pnpm\\dist\\node_modules\\node-gyp',
> │ gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Administrator\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\20.9.0\\\\<(target_arch)\\\\node.lib',
> │ gyp info spawn args   '-Dmodule_root_dir=C:\\dev\\zt-autotestweb\\node_modules\\.pnpm\\@curlconverter+tree-sitter-bash@0.0.3\\node_modules\\@curlconverter\\tree-sitter-bash',
> │ gyp info spawn args   '-Dnode_engine=v8',
> │ gyp info spawn args   '--depth=.',
> │ gyp info spawn args   '--no-parallel',
> │ gyp info spawn args   '--generator-output',
> │ gyp info spawn args   'C:\\dev\\zt-autotestweb\\node_modules\\.pnpm\\@curlconverter+tree-sitter-bash@0.0.3\\node_modules\\@curlconverter\\tree-sitter-bash\\build',
> │ gyp info spawn args   '-Goutput_dir=.'
> │ gyp info spawn args ]
> │ Traceback (most recent call last):
> │   File "C:\Users\Administrator\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\node-gyp\gyp\gyp_main.py", line 42, in <module>
> │     import gyp  # noqa: E402
> │     ^^^^^^^^^^
> │   File "C:\Users\Administrator\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 9, in <module>
> │     import gyp.input
> │   File "C:\Users\Administrator\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 19, in <module>
> │     from distutils.version import StrictVersion
> │ ModuleNotFoundError: No module named 'distutils'
> │ gyp ERR! configure error 
> │ gyp ERR! stack Error: `gyp` failed with exit code: 1
> │ gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\node-gyp\lib\configure.js:325:16)
> node_modules/.pnpm/tree-sitter@0.20.6/node_modules/tree-sitter: Running install script, failed in 13.6s

distutils is removed in Python 3.12 
https://github.com/nodejs/node-gyp/issues/2869

**Comment by verhovsky** [comment]
Which command specifically are you running and what's your node version? I can install it just fine on macOS 14.3:

```
/tmp/cctest$ npm init -y
Wrote to /private/tmp/cctest/package.json:

{
  "name": "cctest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


/tmp/cctest$ npm install curlconverter

added 55 packages, and audited 56 packages in 16s

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
/tmp/cctest$ python --version
Python 3.12.1
/tmp/cctest$ node --version
v21.6.0
```

**Comment by verhovsky** [comment]
What command specifically are you running and which Node version are you using? I can install curlconverter (both as a dependency and clone it and `npm install`) just fine on macOS 14.3 with Python 3.12 and Node 21:

```
$ cd /tmp
/tmp$ git clone git@github.com:curlconverter/curlconverter.git --quiet
/tmp$ cd curlconverter
/tmp/curlconverter$ npm install

> curlconverter@4.9.0 prepare
> husky install && npm run compile && tree-sitter build-wasm node_modules/@curlconverter/tree-sitter-bash && mv tree-sitter-bash.wasm dist/

husky - Git hooks installed

> curlconverter@4.9.0 compile
> tsc


added 381 packages, and audited 382 packages in 48s

146 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
/tmp/curlconverter$ cd ..
/tmp$ mkdir ccinstalltest
/tmp$ cd ccinstalltest/
/tmp/ccinstalltest$ npm init -y
Wrote to /private/tmp/ccinstalltest/package.json:

{
  "name": "ccinstalltest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


/tmp/ccinstalltest$ npm install curlconverter

added 55 packages, and audited 56 packages in 16s

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
/tmp/ccinstalltest$ python --version
Python 3.12.1
/tmp/ccinstalltest$ node --version
v21.6.0
/tmp/ccinstalltest$ npm --version
10.2.4
```

**Comment by verhovsky** [comment]
https://github.com/prebuild/prebuild/issues/313

**Comment by andchir** [comment]
@edisonyan  curlconverter for Python - very bad. Use curlparser instead.

**Comment by Viper373** [comment]
> You'll have to downgrade Python until [prebuild/prebuild#313](https://github.com/prebuild/prebuild/issues/313) is fixed.您必须降级 Python，直到修复为止 [prebuild/prebuild#313](https://github.com/prebuild/prebuild/issues/313) 。

Hello, if I want to run curlconverter using subprocess in python, what version of nodejs, python is required respectively, please let me know, thanks!

**Comment by verhovsky** [comment]
@Viper373 Python 3.11 or older and any Node version.

**Comment by Viper373** [comment]
> @Viper373 Python 3.11 or older and any Node version.Python 3.11 或更早版本以及任何 Node 版本。

thank you very much!
