### ISSUE TITLE
[r] require-vs-library

### ISSUE THREAD

**Issue by r2evans** [curlconverter/curlconverter#636]
The suggested R code starts with `require(httr)`. While that _may_ work, it is misusing the `require` function, as it can return `FALSE` (the package is not installed/available) but provide no error to the user. It is almost always better (especially in this type of use) to use `library(httr)` instead, as it will emit an error if the function is not available.

An alternative is

```r
if (!require("httr")) {
  # do something here, perhaps
  install.packages("httr")
  library(httr)
}
```

Refs: 

- https://stackoverflow.com/a/51263513/3358272
- https://yihui.org/en/2014/07/library-vs-require/
- https://r-pkgs.org/namespace.html#search-path

Thanks.

**Comment by verhovsky** [comment]
Thanks, I changed it to `library(httr)` in https://github.com/curlconverter/curlconverter/commit/07559b5c44c24cf15ad236aec56d36957d32c92c and https://github.com/curlconverter/curlconverter/commit/598d3c4a5a58ac97b0662d338490e835f74edcea .
