### ISSUE TITLE
Support -x flag in curl for NodeJS requests

### ISSUE THREAD

**Issue by nissimlavy** [curlconverter/curlconverter#65]
The -x (--proxy) flag in curl allows you to set the proxy. Can we add the ability to convert a curl request with a proxy flag to NodeJS

**Comment by verhovsky** [comment]
Seems like we need to use https://github.com/TooTallNate/node-https-proxy-agent and generate code like this

```js
var fetch = require('node-fetch');
var HttpsProxyAgent = require('https-proxy-agent');

var proxyAgent = new HttpsProxyAgent('http://<the IP>:<the port>');
var response = await fetch('https://example.com/', { agent: proxyAgent});
```
