### ISSUE TITLE
Vite and WASM files

### ISSUE THREAD

**Issue by wscourge** [curlconverter/curlconverter#661]
I'd love an example on how to use the package with Vite - can't get it quite right as of yet. Here's what I've tried so far:

_vite.config.ts_
```
import { defineConfig } from "vite"
import { viteStaticCopy } from "vite-plugin-static-copy"

export default defineConfig(async () => ({
  plugins: [
    // ...other plugins
    viteStaticCopy({
      targets: [
        {
          src: 'node_modules/web-tree-sitter/tree-sitter.wasm',
          dest: 'public/tree-sitter.wasm',
        },
        {
          src: 'node_modules/curlconverter/dist/tree-sitter-bash.wasm',
          dest: 'public/tree-sitter-bash.wasm',
        },
      ],
    }),
  ],
  // ...other config
}));
```

But I'm not sure what else I need to do. In my React code, I do the following

```
import * as cURL from "curlconverter"

const Try = () => {
  return (<button onClick={() => cURL.toAnsible("curl example.com")}>curlconverter</button>)
}
```

The errors I get when trying to it

> [Error] Unhandled Promise Rejection: TypeError: Load failed
> [Warning] wasm streaming compile failed: TypeError: Unexpected response MIME type. Expected 'application/wasm' (curlconverter.js, line 271)
> [Warning] falling back to ArrayBuffer instantiation (curlconverter.js, line 271)
> [Warning] failed to asynchronously prepare wasm: CompileError: WebAssembly.Module doesn't parse at byte 0: module doesn't start with '\0asm' (curlconverter.js, line 260)
> [Warning] Aborted(CompileError: WebAssembly.Module doesn't parse at byte 0: module doesn't start with '\0asm') (curlconverter.js, line 202)
> [Error] Unhandled Promise Rejection: RuntimeError: Aborted(CompileError: WebAssembly.Module doesn't parse at byte 0: module doesn't start with '\0asm'). Build with -sASSERTIONS for more info.

any help/advice would be much appreciated - thanks!

**Comment by verhovsky** [comment]
Check the Network tab of the devtools to see what file path is actually getting requested and the actual data being sent. I bet it's sending an HTML 404 page, which is obviously not a valid WASM file. Check the layout of the build directory (does Vite have something like that?) to see where the actual file is requested from. Both Wasm files need to be served from the root of your website, like localhost:8888/tree-sitter.wasm and localhost:8888/tree-sitter-bash.wasm

**Comment by wscourge** [comment]
> Check the Network tab of the devtools to see what file path is actually getting requested and the actual data being sent. I bet it's requesting localhost:8888/tree-sitter.wasm and getting an HTML 404 page, which is obviously not a valid WASM file. Check the layout of the build directory (does Vite have something like that?) to see where the actual file is placed, it looks like it'll be localhost:8888/public/tree-sitter.wasm. curlconverter needs both Wasm files to be served from the root of your website, like localhost:8888/tree-sitter.wasm and localhost:8888/tree-sitter-bash.wasm

Here's my Network tab (it's Safari, as I use it in my Tauri app):

![image](https://github.com/curlconverter/curlconverter/assets/16985871/55ecbfce-a14b-4691-89c4-6e4b0f7f4a89)

the response is HTTP 200, but only one file is _tree-sitter.wasm_ (and not _tree-sitter-bash.wasm_ - is that a problem?) is requested. It seems that whatever's placed at the _public_ directory in Vite, is successfully served at the root.

**Comment by wscourge** [comment]
I confirmed that files placed in the _public_ directory are successfully served at the project's root. However, in my network tab, I can see a single _tree-sitter.wasm_ request, that's falsely HTTP 200, as it is sent to http://localhost:1420/**index.html/**tree-sitter.wasm for the reason uknown:

![image](https://github.com/curlconverter/curlconverter/assets/16985871/883fb32e-6a8a-4593-8a86-c225209551c5)

and (correctly) responds with my _index.html_ file:

![image](https://github.com/curlconverter/curlconverter/assets/16985871/9bda6ff2-22eb-4fee-bb7e-2807418fbfcd)

Do you have any idea why does it send an /index.html-prefixed request?

**Comment by verhovsky** [comment]
It's 200 because Vite and other single-page app frameworks handle the URL in JavaScript, so it just always returns index.html which contains some js that then determines that the user should be shown a 404 page after all.

To make it load /tree-sitter.wasm instead of /index.html/tree-sitter.wasm , you could fork curlconverter and then change this 

https://github.com/curlconverter/curlconverter/blob/cf2aab4ce918792a2ae8ad9d689f1c4fac74becb/src/shell/webParser.ts#L7

to

```js
await Parser.init({
  locateFile(scriptName: string, scriptDirectory: string) {
    return scriptName;
  },
});
```

https://github.com/tree-sitter/tree-sitter/tree/master/lib/binding_web#running-wasm-in-browser

**Comment by wscourge** [comment]
Seems like a sane default for this package tho, doesn't it? You already require it to be at the server root, so it only makes sense to actually ignore the `scriptDirectory` altogether, right?

**Comment by verhovsky** [comment]
guess so.

**Comment by verhovsky** [comment]
So it turns out that tree-sitter (Emscripten-compiled Wasm in general) loads tree-sitter.wasm relative to the directory of the JavaScript file that loads it, not relative to the HTML file that includes the JavaScript that loads it. I didn't even know that was possible.

https://github.com/emscripten-core/emscripten/blob/228af1a7de1672b582e1448d4573c20c5d2a5b5a/src/shell.js#L242

So right now curlconverter requests these two URLs

```
require('url').fileURLToPath(new URL('./', import.meta.url)) + 'tree-sitter.wasm';
'/tree-sitter-bash.wasm';
```

We could change it to (as you suggest and as the documentation [claims](https://github.com/curlconverter/curlconverter/blob/cf2aab4ce918792a2ae8ad9d689f1c4fac74becb/README.md#usage-as-a-library) it works)

```
'/tree-sitter.wasm';
'/tree-sitter-bash.wasm';
```

or we could do what I tried to do in #649 properly

```
require('url').fileURLToPath(new URL('./', import.meta.url)) + 'tree-sitter.wasm';
require('url').fileURLToPath(new URL('./', import.meta.url)) + 'tree-sitter-bash.wasm';
```

**Comment by verhovsky** [comment]
Where are your JavaScript files being loaded from, `http://localhost:1420/index.html/main.js` ? or ` http://localhost:1420/main.js`? Or do you have multiple JavaScript files?

**Comment by wscourge** [comment]
I've got the following in my _index.html_:

```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <!-- <link rel="icon" type="image/svg+xml" href="/vite.svg" /> -->
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0" /> -->
    <title>SafeUtils</title>
  </head>

  <body style="overflow:hidden">
    <div id="root" class="windowfocus"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>

```

Found in devtools:

![image](https://github.com/curlconverter/curlconverter/assets/16985871/6520d8bd-f2ce-4d66-8d2c-c84ba1fc1009)

and the _src/main.tsx_ is a pretty standard React setup:

```
import ReactDOM from "react-dom/client";
import App from "./App";

saveWindowState(StateFlags.ALL);
restoreStateCurrent(StateFlags.ALL);

const container = document.getElementById("root") as HTMLElement

ReactDOM.createRoot(container).render(<App />);
```

Here's the _index.html_ in Devtools:
![image](https://github.com/curlconverter/curlconverter/assets/16985871/c9f5bd8c-9686-40a2-899e-32d484db06b4)

As you can see, there are 2 additional Vite's `<script />` tags at the top. 

This is development environment, I haven't run it on prod yet.

So to answer that:

> do you have multiple JavaScript files?

I do have multiple typescript files, I don't know how Vite handles that tho.

**Comment by verhovsky** [comment]
Go to the Sources tab, find web-tree-sitter/tree-sitter.js , unminify it (`{ }` button bottom left), look for "scriptDirectory" and set a breakpoint here

```js
                function locateFile(e) {
                    return Module.locateFile ? Module.locateFile(e, scriptDirectory) : scriptDirectory + e
                }
```

and check the value of `scriptDirectory`

<img width="1440" alt="Screenshot 2024-05-23 at 09 54 26" src="https://github.com/curlconverter/curlconverter/assets/5687998/9b620789-c84c-46fc-9b3c-b9ebc96737af">

Then we need to understand why the value of `scriptDirectory` is `http://localhost:1420/index.html/` when it should be `http://localhost:1420/src/`, since that's where your main.tsx is coming from, which you can do by running this code that it runs to set it in the JS Console

```js
(ENVIRONMENT_IS_WEB || ENVIRONMENT_IS_WORKER) && (ENVIRONMENT_IS_WORKER ? scriptDirectory = self.location.href : void 0 !== document && document.currentScript && (scriptDirectory = document.currentScript.src);
scriptDirectory = 0 !== scriptDirectory.indexOf("blob:") ? scriptDirectory.substr(0, scriptDirectory.replace(/[?#].*/, "").lastIndexOf("/") + 1) : "";
```

and debugging it.

I'm guessing that it's running in a [web worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers), so it's doing `self.location.href` instead of `document.currentScript.src`.

**Comment by verhovsky** [comment]
Let me know if 4.10.0 doesn't fix your issue

**Comment by wscourge** [comment]
After the update, I get this:

> TypeError: "" cannot be parsed as a URL.

![image](https://github.com/curlconverter/curlconverter/assets/16985871/b0d972da-5b46-477b-9ae0-a7b5c261ed7b)

![image](https://github.com/curlconverter/curlconverter/assets/16985871/fe04a0fe-2c9c-453d-95c8-ff3561155c2a)

**Comment by wscourge** [comment]
It makes sense that the code uses `self.location.href` - here's what I see in the console:

![image](https://github.com/curlconverter/curlconverter/assets/16985871/eda9159d-ae4b-4b11-9dda-b57ee7637cce)

the `/#/` comes from react-router-dom package's hash router and is later treated as a URL fragment I guess, leaving the `/index.html`.

**Comment by wscourge** [comment]
I tried inspecting the Sources tab as you described, but the Pretty print is disabled for some reason. I think that checking the `self.location.href` answers your question though.

**Comment by verhovsky** [comment]
Actually it's not using `location.href`, it's using `document.currentScript.src` and the issue is actually this part `type="module"`

> The Document.currentScript property returns the <script> element whose script is currently being processed and **isn't a JavaScript module.**

https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript

So my idea of using `new URL()` doesn't work.
