### ISSUE TITLE
curl convert to json error

### ISSUE THREAD

**Issue by Wang-Jun-Chao** [curlconverter/curlconverter#666]
Error: found "variable_assignment" AST node, only "command", "pipeline" or "redirected_statement" are supported
curl www.baidu.com/a/b/c?x=1&c=3
                             ^^^

![image](https://github.com/curlconverter/curlconverter/assets/13402670/6520d2a7-3ea7-4ba1-ba1f-197ec3b638af)

**Comment by verhovsky** [comment]
put the url in quotes

```sh
curl 'www.baidu.com/a/b/c?x=1&c=3'
```

it won't work as a command either
