### ISSUE TITLE
error when translating curl to python

### ISSUE THREAD

**Issue by callmedaaanger** [curlconverter/curlconverter#676]
Error: Bash parsing error on line 2:
  -H ^"sec-ch-ua: ^\^"Not)A;Brand^\^";v=^\^"99^\^", ^\^"Google Chrome^\^";v=^\^"127^\^", ^\^"Chromium^\^";v=^\^"127^\^"^" ^
                         ^^

**Comment by verhovsky** [comment]
You clicked "Copy as cURL (cmd)" instead of "Copy as cURL (bash)".

#143
