### ISSUE TITLE
Can I compile it into a standalone JS file using Browserify

### ISSUE THREAD

**Issue by ClearSeve** [curlconverter/curlconverter#684]
I encountered an error while compiling
```
browserify index.js -o bundle.js

E:\expansion\index.js:1
import curlconverter from 'curlconverter';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

**Comment by verhovsky** [comment]
curlconverter is an ES6 module because it uses top-level `await`. It seems that browserify doesn't support ES6 modules so it won't work until https://github.com/browserify/browserify/issues/1186 is fixed
