### ISSUE TITLE
curlconverter adds content-type even if original request doesn't have any

### ISSUE THREAD

**Issue by mirochu** [curlconverter/curlconverter#690]
Headers from firefox:
![](https://github.com/user-attachments/assets/333892ed-89db-4f9e-a564-8a5a44c42f59)
Headers from curlconverter:
![immagine](https://github.com/user-attachments/assets/62ccb1ac-47e0-4a15-b860-88c594f12ed1)

**Comment by verhovsky** [comment]
what's the original curl command? firefox is probably generating a curl command that implicitly adds a content type.

**Comment by mirochu** [comment]
Oh yeah, i forgot the command:
```curl 'https://cwip-shaka-proxy.appspot.com/no_auth' --compressed -X POST -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/127.0' -H 'Accept: */*' -H 'Accept-Language: it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3' -H 'Accept-Encoding: gzip, deflate, br, zstd' -H 'Origin: https://bitmovin.com' -H 'Connection: keep-alive' -H 'Referer: https://bitmovin.com/' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: cross-site' --data-raw "DATA"```
As you can see there isn't that header

**Comment by verhovsky** [comment]
If we run a netcat server

```sh
nc -kl 8888
```

and change the command to send a request to it

```sh
curl 'http://localhost:8888/no_auth' --compressed -X POST -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/127.0' -H 'Accept: */*' -H 'Accept-Language: it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3' -H 'Accept-Encoding: gzip, deflate, br, zstd' -H 'Origin: https://bitmovin.com' -H 'Connection: keep-alive' -H 'Referer: https://bitmovin.com/' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: cross-site' --data-raw "DATA"
```

we can see that curl does send that header

```http
POST /no_auth HTTP/1.1
Host: localhost:8888
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/127.0
Accept: */*
Accept-Language: it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br, zstd
Origin: https://bitmovin.com
Connection: keep-alive
Referer: https://bitmovin.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
Content-Length: 4
Content-Type: application/x-www-form-urlencoded

DATA
```

so this is a bug in Firefox's generation of curl commands, it needs to account for implicit curl headers https://hg.mozilla.org/mozilla-central/file/tip/devtools/client/shared/curl.js

**Comment by verhovsky** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1921645
