### ISSUE TITLE
The format of the data is wrong

### ISSUE THREAD

**Issue by liuchangzong** [curlconverter/curlconverter#691]
I have just copy a post in browser like 'copy as curl(cmd)'.
Then I put it into the curlconverter.com website and got a python script.
I found that this python script got a 404 response while the curl cmd worked well.
It is OK to use `--data-raw "{""lkcId"":""xx"",""isShowHideLabel"":0}"` in curl command, but it is not OK to use `data = '{lkcId:,isShowHideLabel:0}'` in Python script. The format conversion is incorrect and needs to be changed to `data = '{"lkcId":"","isShowHideLabel":0}'`.
The most strange thing is that even  `data = "{'lkcId':'','isShowHideLabel':0}"` does not work.

**Comment by verhovsky** [comment]
Please post the curl command

**Comment by liuchangzong** [comment]
`curl "https://xx" -X POST -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0" -H "Accept: application/json, text/plain, */*" -H "Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2" -H "Accept-Encoding: gzip, deflate, br, zstd" -H "Content-Type: application/json;charset=utf-8" -H "Origin: https://xx" -H "Connection: keep-alive" -H "Referer: https://xx" -H "Cookie: JSESSIONID=xx; SERVERID=xx" -H "Sec-Fetch-Dest: empty" -H "Sec-Fetch-Mode: cors" -H "Sec-Fetch-Site: same-origin" -H "Priority: u=0" --data-raw "{""lkcId"":""xx"",""isShowHideLabel"":0}"`

**Comment by verhovsky** [comment]
Where did you get this curl command from? Wherever it's from is generating bad commands, the conversion is correct.
