### ISSUE TITLE
Support username:password in URL

### ISSUE THREAD

**Issue by kishore0709** [curlconverter/curlconverter#77]
Hi Nick,

I'm not able to convert below curl command to python requests. Could you please help in resolve this.  Thanks!

curl -XPUT username:password@localhost:port/_snapshot/my_backup -d '{ "type": "swift", "settings": { "swift_url": "http://someurl.com:port", "
swift_container": "backup", "swift_username": "test", "swift_password": "testing" }}'

**Comment by NickCarneiro** [comment]
It looks like we don't supprt username:password in the url like you'd
expect. It works if you rework it a little:
curl -XPUT http://localhost:port/_snapshot/my_backup -u username:password
-d '{ "type": "swift", "settings": { "swift_url": "http://someurl.com:port",
"
swift_container": "backup", "swift_username": "test", "swift_password":
"testing" }}'

import requests

data = '{ "type": "swift", "settings": { "swift_url":
"http://someurl.com:port", "\nswift_container": "backup", "swift_username":
"test", "swift_password": "testing" }}'

response = requests.post('http://localhost/:port/_snapshot/my_backup',
data=data, auth=('username', 'password'))

**Comment by verhovsky** [comment]
Closing as duplicate of #222
