### ISSUE TITLE
Query strings with percent signs fail to parse

### ISSUE THREAD

**Issue by shellvon** [curlconverter/curlconverter#78]
```bash
curl 'http://chengyu.t086.com/chaxun.php?q1=%C8%CB&q2=&q3=&q4=' -H 'Pragma: no-cache' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8' -H 'Referer: http://chengyu.t086.com/chaxun.php?q1=chi' -H 'Cookie: __cfduid=d6b3c871bf9e8287df0889c3e6e4d1a241514973157; Hm_lvt_39ac3afc91754c24e2deef3c40478571=1514973163,1515071805; cf_clearance=c27a2194be0b403bc27508929b67c42ec97e21ac-1515075089-1800; yjs_id=fDE1MTUwNzU2NzQ2MzI; Hm_lpvt_39ac3afc91754c24e2deef3c40478571=1515075675' -H 'Connection: keep-alive' -H 'Cache-Control: no-cache' --compressed
```

**Comment by NickCarneiro** [comment]
This seems like a pretty big problem in the browser. The difference in behavior probably has to do with native query string parsing in the browser vs node.js.

**Comment by jghjgfgh** [comment]
I also got this issue with `--data-binary`. Minimal example:
```
curl 'https://www.upwork.com/ab/account-security/login' --data-binary '%'
```

**Comment by verhovsky** [comment]
4 years later, we can parse both of these commands.

The only issue is the `%C8%CB` in your URL. That's not a valid percent encoded value, so when we convert that to a Python dictionary we try to decode it, it doesn't work so the string just stays the same (that's how the querystring parsing library we use handles those errors, silently) and we convert it to a Python dict, then we submit that dictionary through requests, it percent encodes it *again* and so the generated code ends up sending slightly different data than what curl sends. The solution is to detect that it's not a valid percent encoded value and leave it as is, part of the URL.
