### ISSUE TITLE
Headers should be in an ordered dict (Python)

### ISSUE THREAD

**Issue by jonluca** [curlconverter/curlconverter#79]
If the goal of curlconverter is _not_ to exactly emulate a browser, then please close this issue.

However, if the goal is to go from something like:

* Browse to a site
* Copy the request as curl from devtools
* Convert curl to Python

And have it be identical requests in an idempotent fashion, then the headers for the python request must be stored in an ordered dict. 

You can see [this issue](https://github.com/requests/requests/issues/3038) for more information.

Some services actually block requests if the order of the headers is not the way they expect - browsers send them in a predictable fashion, but, depending on what headers are used/omitted, requests will not.

**Comment by NickCarneiro** [comment]
Thanks for the detailed description. Will investigate asap.

**Comment by jonluca** [comment]
Thanks! 

Yeah, I'm not 100% sure if this is even a goal for the service. Realistically, in 99% of cases, this won't matter. It's only if we're building a full-fledged browser emulator that this would need to be implemented. 

It should be a fairly simple change though - just change the dict type to an OrderedDict, and preserve the order of the headers as they are passed through the curl request.

Thanks again for the great tool!

**Comment by machine-gurning** [comment]
I would be very appreciative of the same change -- did this ever happen?

**Comment by verhovsky** [comment]
Python dicts preserve insertion order starting with CPython 3.6 or other Python implementations with 3.7, so this should be the case for Python output, unless we're somehow re-ordering the headers while generating the output.
