### ISSUE TITLE
Add support for urls specified after short form arguments are combined and the location has no scheme

### ISSUE THREAD

**Issue by waiterw** [curlconverter/curlconverter#80]
curl -o app/assets/images/rails.png -OL railstutorial.jp/rails.png

**Comment by NickCarneiro** [comment]
The current code makes a faulty assumption that the url will contain a scheme like "http". We need to be looser with the matching so we can find strings like `railstutorial.jp/rails.png`

**Comment by verhovsky** [comment]
Combining single-letter boolean arguments has been supported for a while

```py
import requests

response = requests.get('http://railstutorial.jp/rails.png')
```

The thing that's missing is support for `-o`/`--output` but I don't really want to do that
