### ISSUE TITLE
curl param --data-urlencode is being dropped off

### ISSUE THREAD

**Issue by miguelfg** [curlconverter/curlconverter#85]
Hi, I get from the chrome dev tools > copy as cURL request , a whole command that contains the curl parameter: '--data-urlencode' followed by something like 'start-year=2012&start-month=6&start-day=1&....'

However when i translate this in your web app from cURL to python requests, it seems to translate everything ok, except this parameter.

Thanks for your tool btw.

**Comment by ehb54** [comment]
Same issue converting to node encountered here.  Great tool, I'm starring it. It should be easy to add for node: https://stackoverflow.com/questions/42513285/data-urlencode-curl-to-nodejs-request-or-express-module

**Comment by jdeltoft** [comment]
Yea, I'm having the same issue.  The --data-urlencode isn't being converted on the web tool.  Example input:

    curl -i -XPOST http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"

**Comment by verhovsky** [comment]
We haven't been dropping `--data-urlencode` for a while,


```py
import requests

data = {
  'q': 'CREATE DATABASE mydb'
}

response = requests.post('http://localhost:8086/query', data=data)
```

but we just pass its value as-is, we don't parse it like curl does. It's the most complicated of the `--data` flags https://curl.se/docs/manpage.html#--data-urlencode
