### ISSUE TITLE
Error in converting a valid curl command

### ISSUE THREAD

**Issue by karthikvrsjp** [curlconverter/curlconverter#91]
This is a valid curl command for which a service for host is created. 
curl -XPOST "http://XX.X.XX.XX/nagiosxi/api/v1/config/service?apikey=cU9nkHR5RaYRs%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%7rugfGtOJ&pretty=1" -d "host_name=HOST1&service_description=SERVICE1&check_command=check-host-alive\!3000,80%\!5000,100%&check_interval=5&retry_interval=5&active_checks_enabled=0&max_check_attempts=2&check_period=24x7&contacts=nagiosadmin&notification_interval=5&notification_period=24x7&applyconfig=1"

I am not able to convert it to python request. Please help. Thanks in advance.

**Comment by NickCarneiro** [comment]
Chrome doesn't like the url. Stack trace for to look at later.
![urierror](https://user-images.githubusercontent.com/700209/47611769-41f6ae80-da29-11e8-8af4-0a37c7d5ffd0.png)

Same error affecting https://github.com/NickCarneiro/curlconverter/issues/102
