### ISSUE TITLE
Curl requests with client certificates are not converted correctly in Python

### ISSUE THREAD

**Issue by tinutomson** [curlconverter/curlconverter#97]

**Comment by NickCarneiro** [comment]
Example command?

**Comment by tinutomson** [comment]
curl https://example.com/endpoint -H 'content-type: application/json' -d '{ "data": "data" }' --cert /path/to/cert --key /path/to/key

**Comment by xatier** [comment]
`--cacert` also doesn't seem correct.

**Comment by HerHde** [comment]
Very handy project, thank you, @NickCarneiro!

> `curl https://example.com/endpoint -H 'content-type: application/json' -d '{ "data": "data" }' --cert /path/to/cert --key /path/to/key`

Should translate to  something like

```python
import requests

headers = {
    'content-type': 'application/json',
}

cert=('/path/to/cert', '/path/to/key')

data = '{ "data": "data" }'

response = requests.post('https://example.com/endpoint', headers=headers, cert=cert, data=data)
```

whereas omitting `--key` should result in `cert='/path/to/cert'`.

Related docs: https://2.python-requests.org/en/master/user/advanced/#client-side-certificates
